### ISSUE TITLE
White modal blends with white backgrounds

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-launcher-electron#153]
On Windows, a border or drop shadow is needed to define the Installer
@sheadarlison FYI

Reference:
![img_20160126_141042](https://cloud.githubusercontent.com/assets/11826611/12590497/432bc486-c431-11e5-8b81-4bc0280eae5d.jpg)

**Comment by btfrise** [comment]
Confirmed as fixed. Love the green border!
