### ISSUE TITLE
When a media player starts with no internet, the installer shows 2 "Unknown Errors" until the network is connected.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#155]
<b>How it works now:</b>
1. install Rise Vision Player on a Display, confirm it starts running and asks for a Display ID.
2. Remove the network connection and reboot. Notice that you get the installer window with "An unknown error has occurred" listed twice:
![2016-01-29_15-26-30](https://cloud.githubusercontent.com/assets/6862256/12687961/165b6840-c6a1-11e5-9df0-f145bdce5838.png)

Plug the network back in, and notice that after roughly 5 minutes, the installer window disappears, and the player starts.

<b>How it should work:</b>
The error message should state that there is no network connection and it will keep trying, not that an unknown error has occurred.

**Comment by tejohnso** [comment]
@robb-price Is there a display id for that test?

**Comment by robb-price** [comment]
@tejohnso Yup:
CH7UUAD89XJS
TQS5KSJQ42XE

**Comment by tejohnso** [comment]
@robb-price I'm looking at the logs for those displays and they look fine.  Is this happening today?

**Comment by robb-price** [comment]
@tejohnso Yes.

**Comment by ahmedalsudani** [comment]
To test this has been fixed:

- uninstall the player
- disconnect the network
- run the v3 installer
- ensure you receive a proxy message

**Comment by btfrise** [comment]
This is fixed on the lnx-64 installer.

**Comment by robb-price** [comment]
Confirmed on the Win 32 Installer.

**Comment by btfrise** [comment]
Confirmed as fixed.
