### ISSUE TITLE
Starting Player/Installer with the --unattended flag adds the Player to the Startup folder

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#156]
<b>How it works now:</b>
1. Install Player and deselect the option to have it start up with the OS. Notice that it does not start with the operating system.
2. Start the installer from C:\Users\%Username%\AppData\Local\rvplayer\Installer\with the --unattended flag. In Linux, from the home\rvplayer folder. Notice that since you can't deselect the "Add to Startup Process" option, it is now set added to your Startup applications.

<b>How it should work:</b>
Unattended should not add the Rise Vision Player to the Startup Applications.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vgEYYH7S&#x2F;883-don-t-force-autostart-in-unattended-mode-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Don&#39;t force autostart in unattended mode [1]</a>

**Comment by ahmedalsudani** [comment]
To verify this has been fixed:

- Run the v3 installer 
- Uncheck "Add to startup process" and finish the installation
- Restart the computer
- Navigate to the rvplayer directory in the command line* and run (`./Installer/installer`)

* In Ubuntu, the directory is `~/rvplayer`. In Windows, it's `<user_home>/AppData/Local/rvplayer`. If there's an issue, please get in touch with me :)

**Comment by btfrise** [comment]
Confirmed fixed.
