### ISSUE TITLE
Installer hangs at "setting autostart" when expected startup directory is not found.

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#157]
This was found on windows 7 pro 32bit

To reproduce:

Make sure there is no `startup` directory in `users/username/appdata/roaming/microsoft/windows/start menu/programs`

Start the installer

It will get stuck at "setting autostart".

It should not get stuck.

**Comment by tejohnso** [comment]
@ashleighalmeida FYI card created here https://trello.com/c/r4SPlbVi

**Comment by tejohnso** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;r4SPlbVi&#x2F;887-issue-157-installer-hangs-at-setting-autostart-when-expected-startup-directory-is-not-found"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue #157: Installer hangs at &quot;setting autostart&quot; when expected startup directory is not found.</a>

**Comment by ashleighalmeida** [comment]
@tejohnso Thanks!

**Comment by ashleighalmeida** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1838388049

**Comment by btfrise** [comment]
Confirmed fixed.
