### ISSUE TITLE
Links open inside Electron

### ISSUE THREAD

**Issue by ahmedalsudani** [Rise-Vision/rise-launcher-electron#169]
Right now, external links open inside electron

We need to stop that from happening.

Options:

- copy them to clipboard
- open them in external browser
- noop

**Comment by robb-price** [comment]
To validate: 
1. Run the Installer
2. Click on the link for the community in the Electron installer
3. Confirm that an external browser window opens and goes to the community.

**Comment by hcs0** [comment]
verified on the new installer for Ubuntu 14.04 x32 x64

**Comment by hcs0** [comment]
verified on new installer for win 7 x32 x64
