### ISSUE TITLE
'Restart Rise Vision Player' requires user input to restart player.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#173]
**How to recreate**
1. Install ver3 Rise Vision Player (https://storage.googleapis.com/install-versions.risevision.com/backups/staging/2016.2.8/installer-win-64.exe)
2. Add a display ID, and launch a presentation.
3. Close player with control+w, or 'Stop Rise Vision Player' from start menu.
4. Select 'Restart Rise Vision Player' from start menu

**What happens**
The launcher opens the install window, which prompts users to click Continue twice to open Rise Player.

**What should happen**
Rise Player should restart with no user intervention.

**Notes**
Currently tested on Windows 10 64bit

**Comment by btfrise** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IltvxH43&#x2F;1396-2-installer-testing-on-win10-64-bit"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) Installer Testing on Win10 64 Bit</a>

**Comment by ByronDarlison** [comment]
This is not something that we want to change as of this point in time. Thanks
