### ISSUE TITLE
Install process crashes on shortcut link rename

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#176]
If a user is attempting to install to a foreign destination with no permission, the install process will halt with an error message.  We should not stop the install in this case, we should log the error and continue.

{ message: 'Error renaming file', error: { [Error: EXDEV: cross-device link not permitted, rename 'C:\Users\kchung\AppData\Local\rvplayer\Uninstall Rise Vision Player.lnk' -> '\\sau-file\sau-staff-profiles$\kchung\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Rise Vision\Uninstall Rise Vision Player.lnk'] errno: -4037, code: 'EXDEV', syscall: 'rename', path: 'C:\\Users\\kchung\\AppData\\Local\\rvplayer\\Uninstall Rise Vision Player.lnk', dest: '\\\\sau-file\\sau-staff-profiles$\\kchung\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Rise Vision\\Uninstall Rise Vision Player.lnk' } }

**Comment by robb-price** [comment]
@tejohnso @fjvallarino @ahmedalsudani How would CS go about verifying this?

**Comment by fjvallarino** [comment]
@robb-price It's difficult to test. The user apparently has its Home folder mapped to a network drive (which probably is something you can do with Windows Network/Enterprise policies). We were able to replicate the issue in a programmatic way (it's a Node.js issue, which fails when renaming a file in one file system to a different one, so renaming "c:\file.txt" to "d:\file.txt" gives that error message).

**Comment by ahmedalsudani** [comment]
@fjvallarino could we change an environment variable so that `LOCALAPPDATA` points to a directory on `D:\`?

/cc @robb-price

**Comment by fjvallarino** [comment]
@ahmedalsudani I tried that changing the variable from the command line and running installer.exe too, but it did not work.

**Comment by tejohnso** [comment]
@ahmedalsudani @fjvallarino We can close this now right?

**Comment by fjvallarino** [comment]
I think @btfrise confirmed this one
