### ISSUE TITLE
Users cannot use Alt-Tab to switch to the installer window

### ISSUE THREAD

**Issue by ahmedalsudani** [Rise-Vision/rise-launcher-electron#187]

**Comment by tejohnso** [comment]
@ahmedalsudani @btfrise Is this resolved now?

**Comment by ahmedalsudani** [comment]
@tejohnso no, at least I haven't fixed it yet. 

Branch [fix/taskbar-icon](https://github.com/Rise-Vision/rise-launcher-electron/tree/fix/taskbar-icon) fixes it, but it's missing an icon -- it display's Electron's icon in the taskbar.

**Comment by ByronDarlison** [comment]
@tejohnso @ahmedalsudani what is this plan for this defect?

**Comment by ByronDarlison** [comment]
Ignore the above, found the card for it. Thanks

**Comment by ByronDarlison** [comment]
@tejohnso @ahmedalsudani I would prefer to close this issue and not fix it. Let me know if you concur.

**Comment by ahmedalsudani** [comment]
@ByronDarlison do you mean mark is as a non-bug? I'm ok with that

**Comment by ByronDarlison** [comment]
Not worth fixing
