### ISSUE TITLE
Upon closing player after installation, you get a `mainWindow = null` error

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#217]
**How to recreate**
1. Install test ver3 Rise Vision Player (https://storage.googleapis.com/install-versions.risevision.com/backups/staging/2016.3.10/installer-win-64.exe).
2. Once installation completes, close player with control+w

**What happens**
A pop up appears:
![2016-03-11-162636_2704x1280_scrot](https://cloud.githubusercontent.com/assets/5868781/13748408/1c9e65f4-e9d3-11e5-8b68-a542bea2d429.png)

**What should happen**
No Javascript related pop up error messages appearing when exiting the Player.  

**Notes**
Currently tested on Windows 7 x64.
Another pop up appeared referencing an rvplayer folder that was in a Temp folder.  This error message is referencing the current rvplayer folder.

**Comment by tejohnso** [comment]
@hcs0 this doesn't happen all the time, correct?

**Comment by robb-price** [comment]
@hcs0 Does the installation complete? When do you close it with Control + w?

**Comment by hcs0** [comment]
@tejohnso It happened three times on Win 7x64 on the particular machine that I am on. 
@robb-price This is after completing the install

**Comment by hcs0** [comment]
A user's Display showed the error message.

**How to recreate**
1. Install stable Win x64 on Win 7
2. Ctrl+W to exit 

<img width="418" alt="screen shot 2016-03-14 at 3 59 10 pm" src="https://cloud.githubusercontent.com/assets/5868781/13758059/cfe6706e-e9fd-11e5-959e-9b777a11ec16.png">

**Comment by robb-price** [comment]
Does not occur on Win 7 32 Bit.

**Comment by hcs0** [comment]
does not occur win 7x64

**Comment by hcs0** [comment]
does not occur on win 10 x64
