### ISSUE TITLE
'Unknown error' when upgrading frm V3 stable to V3 test installer.

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#218]
**How to recreate**
1. Install existing supported Player from Create a Display page 
2. Close player with control+w 
3. Run the test installer file (https://storage.googleapis.com/install-versions.risevision.com/backups/staging/2016.3.10/installer-win-64.exe) to run through and test the upgrade process from the V3 stable to the V3 test installer.

**What happens**
Unknown error message appears.  See installer-detail.log
https://trello-attachments.s3.amazonaws.com/536265d788e5199d704e018a/56e2e3682c7486b66a812e3c/8a18987dd18aa82901ac8b7e1431b433/installer-detail-UpgradeV3stabletonew-Win7x64.txt 

**Notes**
Currently tested on Windows 7 x64.
The unknown error message has only occurred once and on this machine.
The unknown error message occurred right after the Javascript pop up error message https://github.com/Rise-Vision/rise-launcher-electron/issues/217 
I was able to go through an re-install again without seeing this error message occur again.

**Comment by robb-price** [comment]
@hcs0 @ahmedalsudani If it has only happened once, and only on this machine, do we need to correct this? It doesn't sound like we can recreate anywhere else, is that accurate?

**Comment by hcs0** [comment]
@robb-price I was able to move past this and finish the rest of the tests so may have been a once only issue.

**Comment by robb-price** [comment]
@hcs0 Thanks. @ahmedalsudani Given that, do we need to investigate this?

**Comment by ahmedalsudani** [comment]
@robb-price I believe so. Looking at the installer logs, it might be possible for us to make an improvement here. At the very least, we can turn this into a "known error."

@fjvallarino @tejohnso FYI.

```js
 { [Error: EBUSY: resource busy or locked, unlink 'C:\Users\user\AppData\Local\rvplayer\Installer\locales\en-US.pak']
    errno: -4082,
    code: 'EBUSY',
    syscall: 'unlink',
    path: 'C:\\Users\\user\\AppData\\Local\\rvplayer\\Installer\\locales\\en-US.pak' },
```

**Comment by robb-price** [comment]
Did not see on Lnx 64 Bit

**Comment by robb-price** [comment]
Unknown error does not show on Win 7 64.

**Comment by hcs0** [comment]
Unknown error does not show on Win 7 x32
