### ISSUE TITLE
Installer runs into EPERM error and hangs when there are two installer.exe processes running with --unattended

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#219]
**How to recreate**
Try to run an installation but have two installer.exe processes running with --unattended

**What happens**
Installer is stuck on 'Installing launcher' UI window.
See <a href="https://s3.amazonaws.com/uploads.hipchat.com/106443/3304309/vOS5FUg8bnVKkh6/installer-detail.log">installer-detail.log</a>.

**What should happen**
The installer should show an error message / maybe finish installing and launch the Player

**Notes**
Occurred on Win 7 x32

**Comment by robb-price** [comment]
@hcs0 @ahmedalsudani Which do we want to do here? Show an error or finish the install?

**Comment by ahmedalsudani** [comment]
@robb-price in this case, we'd want to show an error since it's a severe failure. We have a fix that should be in the next release.

**Comment by robb-price** [comment]
Works on Win 7 32 Bit

**Comment by hcs0** [comment]
works win 7 x64
