### ISSUE TITLE
Chrome process not killed if it's running and installer has started

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#225]
**How to recreate**
Finish the production Ver 3 installer and add the Display ID.  

**What happens**
The presentation will appear followed by the UI window like when the user restarts the Player. A grey screen then appears - the Chrome instance will appear as a grey box with '?' in the Unity Launcher bar.

![greyscreen](https://cloud.githubusercontent.com/assets/5868781/13793397/15452126-eacd-11e5-9eca-31bdb3a546e3.png)

**What should happen**
When launching the installer, there should be no grey screen appearing

**Notes**
Occurred on Ubuntu 14.04 x64
Can be recreated on the command line where pkill is not killing all Chrome tasks

**Comment by hcs0** [comment]
https://trello.com/c/ILcrR95x/1005-issue-225-chrome-process-not-killed-if-it-s-running-and-installer-has-started-2

**Comment by tejohnso** [comment]
@hcs0 Please confirm this is corrected when you're testing the new versions on Monday.

**Comment by hcs0** [comment]
@tejohnso Will do! Saw this again on my Ubuntu display yesterday (grey screen)

**Comment by robb-price** [comment]
Did not see this on Ubuntu 64 bit.

**Comment by btfrise** [comment]
Fixed in Ubuntu 32bit. Closing.
