### ISSUE TITLE
Stop shortcut does not function.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#249]
**OS** Ubuntu 14.04 x32/x64
**Installer** 2016.03.23.14.34

**How to recreate**
1. Install new Rise Player via new installer
2. Launch Rise Player
3. Alt-tab to Unity taskbar
4. Search for Stop
5. Click Stop Rise Vision Player

**What happens**
Rise Player does not stop

**What should happen**
Rise Player and java processes should be killed.

**Comment by robb-price** [comment]
Fixed on Ubuntu 64 Bit.

**Comment by btfrise** [comment]
Fixed on Ubuntu 32bit. Closing.
