### ISSUE TITLE
CMD box shows "ERROR: The system was unable to find the specified registry key or value." during installation.

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#250]
**How to recreate**
Run test Ver 3 installer

**What happens**
After selecting to install .exe
	.	In DOS window with the line 'Copying files' for ~1-2min
	.	In DOS window with the line 'Launching' for ~20 seconds
	.	UI for Rise Player Installation starts

Message within DOS is:
"ERROR: The system was unable to find the specified registry key or value. No Instance<s> Available" 

**What should happen**
When launching the installer, the user should see the UI screen without waiting for 1-2 minutes.

**Notes**
Occurred on Win 7 x32. On Win 7 x64, the DOS window does not stay long (ie 2-3 seconds)

**Comment by fjvallarino** [comment]
@hcs0 @robb-price @tejohnso I don't know if there is actually something we can do about this. We are currently using a command line utility provided by Windows (Robocopy), and we can't really do it much faster than what the OS already provides. This seems to be happening only on Win 32.

**Comment by tejohnso** [comment]
I could not replicate this on the win32 developer test uptime https://connect.risevision.com/Host#*Rise_Developers//224de066-b72c-4c6b-8f2c-9c37f0360f0d

**Comment by robb-price** [comment]
@hannah

**Comment by robb-price** [comment]
@hcs0 I didn't see this for the amount of time you referred to as well on my Windows 7 32 Bit box. It should for roughly 10/12 seconds, and then moved on, so I don't think we have a problem here.

@fjvallarino @tejohnso @ahmedalsudani Is there anything we can do about the "ERROR: The system was unable to find the specified registry key or value." message? I saw the same, and it stands out like a sore thumb, I know someone will bring it up.

**Comment by ahmedalsudani** [comment]
@robb-price we plan on hiding the command prompt window in the next release, so the user shouldn't see this message in the future

**Comment by tejohnso** [comment]
@robb-price given that, can we close this?

**Comment by tejohnso** [comment]
Actually, I think we should close this either way because we're talking about something else now.  We should open a separate issue for the command prompt window if necessary.  @robb-price FYI
