### ISSUE TITLE
graceful_shutdown_flag does not exist.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#251]
**OS** Ubuntu 14.04 x32/x64
**Installer**2016.03.23.14.34

**How to recreate**
1. Install Rise Player using new installer
2. Launch Rise Player
3. Close Rise Player with control+w
4. Navigate to ~/rvplayer/2016.xx.xx.xx.xx

**What happens**
graceful_shutdown_flag does not exist at all in x64. If you navigate up one directory to ~/rvplayer, graceful_shutdown_flag is contained on x32.

**What should happen**
graceful_shutdown_flag should exist in ~/rvplayer/2016.xx.xx.xx.xx

**Comment by fjvallarino** [comment]
@btfrise graceful_shutdown_flag should be in ~/rvplayer, not inside the specific version.

I checked and it's being placed in the correct location when stopping player using the menu option.

**Comment by btfrise** [comment]
@fjvallarino Thanks, I will update the testing document.
