### ISSUE TITLE
Pop up showing "Windows cannot find '--unattended'..." message when you press Restart Player from Display Settings and the Username has a space

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#252]
**How to recreate**
1. Use a Windows machine where the username has a space (ie Rise Vision)
2. Run test Ver 3 installer
3. Press Restart Player from Displays page twice (notice the Player does not restart the first time - see <a href="https://github.com/Rise-Vision/rise-launcher-electron/issues/260">this issue</a>).  

**What happens**
A pop up _"Windows cannot find '--unattended'. Make sure you typed the name correctly, and then try again''_ appears.  

**What should happen**
No pop message

**Notes**
Occurred on Win 7 x32 and Win 7 x64

**Comment by tejohnso** [comment]
@hcs0 I could not replicate this on either win7/64 or win7/32.  Can we screenshare?

**Comment by hcs0** [comment]
@tejohnso I've updated the bug noting that it's on a Windows machine with space in the username and that it occurs when you press Restart Player twice.

**Comment by robb-price** [comment]
Could not recreate on Ubuntu 64 Bit.

**Comment by hcs0** [comment]
Works on Win 7x32

**Comment by robb-price** [comment]
Works on Win 7 64 bit.
