### ISSUE TITLE
'spawn timeout: pkill -f,Rise.*jar' error message is logged in BigQuery for Ubuntu Displays

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#253]
**How to recreate**
1. Run test Ver 3 installer
2. Run the Display ID in BQ to verify installer version.

**What happens**
In BQ for Windows, there is a message 'spawn timeout: taskkill /f,/im,javaw.exe'
In BQ for Linux, there is a message 'spawn timeout: pkill -f,Rise.*jar' http://www.screencast.com/t/Ip1vwU577 

**What should happen**
No BQ error message for Ubuntu

**Notes**
This is expected in Windows, but should not occur in Ubuntu.

**Comment by btfrise** [comment]
**Notes**

This also occurs in Ubuntu 14.04 x32/x64

**Comment by hcs0** [comment]
@btfrise added

**Comment by ahmedalsudani** [comment]
@hcs0 @btfrise we expect to see this on Windows. It's due to a weird quirk where the kill command won't return, so it times out. As long as the viewer starts, it's not a problem.

However, if this occurs on Ubuntu, we have something strange. Can you please confirm it occurred on Ubuntu, @btfrise?

**Comment by btfrise** [comment]
@ahmedalsudani Here is a screenshot of the BQ logs from a lnx64 machine. http://www.screencast.com/t/Ip1vwU577 This error message is actually slightly different, should I log a seperate bug? 

'spawn timeout: pkill -f,Rise.*jar'

**Comment by hcs0** [comment]
@btfrise @ahmedalsudani I've updated the bug report to include your additional notes for Linux message in BQ

**Comment by btfrise** [comment]
This also occurs in Win 10 x64 fyi @hcs0

**Comment by tejohnso** [comment]
@btfrise @hcs0 This will be addressed in the next patch.  Expected for Monday.

**Comment by robb-price** [comment]
Does not show for Ubuntu 64 Bit

**Comment by btfrise** [comment]
Fixed in Ubuntu 32bit. Closing.
