### ISSUE TITLE
--unattended flag results in error.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#254]
**OS** Ubuntu 14.04 x32/x64
**Installer** 2016.03.23.14.34

**How to recreate**
1. Open a terminal window
2. Run ./installer-lnx-32.sh --unattended

**What happens**
Error: Unrecognized flag

**What should happen**
The unattended flag should allow the installer to run with no network.

**Comment by fjvallarino** [comment]
@btfrise the correct syntax is:

./installer-lnx-32.sh -- --unattended

The -- is required by Makeself, the tool we use to build Linux packages, to avoid having it interpret the parameters as instructions to itself (e.g, it allows you to extract the package and not run the installation script)

**Comment by btfrise** [comment]
Thanks @fjvallarino confirmed.
