### ISSUE TITLE
Waiting for Upgrade causes blank Player/Viewer to load.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#255]
**OS** Ubuntu 14.04 x32/x64
**Installer** 2016.03.23.14.34

**How to recreate**
1. Set up Charles Network Proxy w/ a 50% reliable network.
2. Disconnect network
3. Launch installer w/ --rollout-pct=100, at proxy screen input 127.0.0.1/8888
4. Connect network
5. Click continue

**What happens**
Upgrade downloads, no error in BQ. Installer shows "Waiting for upgrade" and never completes. If you click continue, you get a gray Player/Viewer with no loading spinner or content.

**What should happen**
We should see an error reported in BQ. After clicking continue, Player/Viewer should launch and show content.

**Comment by tejohnso** [comment]
@btfrise this sounds about right for a 50% reliable connection :)

The download probably ended up being corrupted, so the "waiting for upgrade" kept waiting for an upgrade that was non functional.   Then after it let the user continue, it launched player, which worked well as evidenced by viewer showing up.   But viewer then couldn't load properly.  Subject to 50% reliability, that's not unexpected.

**Comment by btfrise** [comment]
@tejohnso Thanks for the confirmation! I'll close this bug.
