### ISSUE TITLE
After selecting Uninstall, the rvplayer folder remains, and the DOS window that opens does not close

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#256]
**How to recreate**
1. Run test Ver 3 installer, and complete it to the point where the Player/Viewer is up and running.
2. From the start menu, select uninstall.

**What happens**
The rvplayer folder is not deleted completely, and the DOS window that opens during uninstall does not close automatically. You are not able to delete the rvplayer folder to do another reinstall unless you close the DOS window. 

**What should happen**
After selecting Uninstall, the rvplayer folder is completely removed, and the DOS window should close.

**Notes**
Occurred on Win 7 x32 and Win 7 x64

**Comment by btfrise** [comment]
Just for reference, I did not experience this in Win10 x64.

**Comment by robb-price** [comment]
Does not occur on Ubuntu 64 bit.

**Comment by hcs0** [comment]
does not occur on win 7x32
