### ISSUE TITLE
Installer continues the upgrade from Ver 3 stable to Ver 3 test despite 50% network reliability

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#258]
**How to recreate**
1. Run the installer from the Create a Display Page.
2. Enable 50% network reliabity in Charles or Clumsy
2. Run installer.exe --rollout-pct=100

**What happens**
The upgrade continues to run despite using the 50% Network reliability. The user can press Continue until they get to the Viewer showing.

**What should happen**
The upgrade should fail and inform the user it has failed, and start the previous version of Player.

**Notes**
Occurred on Win 7 x32 and Win 7 x64.

**Comment by tejohnso** [comment]
@hcs0 A 50% network reliability won't cause the installation to outright fail.  It's going to depend on chance at that point.  It's possible that it could still pass the initial checks to connect to the required apis.

**Comment by hcs0** [comment]
@tejohnso I can close this since it's not a bug.

@robb-price I made a note on the test spreadsheet about this part of the test (using Charles/Clumsy to do 50% reliability)
