### ISSUE TITLE
Restart Player from Displays page does not work

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#260]
**How to recreate**
1. Use a Windows machine where the username has a space (ie Rise Vision)
2. Install the Ver 3 test installer
3. Add the Display ID so you have a Presentation up and running.
4. Select the Restart Player button from the Displays page and confirm that you see the message "Restart signal sent"

**What should happen**
The Player should restart

**Notes**
Occurs on Win 7 32/64 bit
If the restart does not occur and the Restart Player button was pressed again on Win 7 32/64 bit this error also appears https://github.com/Rise-Vision/rise-launcher-electron/issues/252

**Comment by btfrise** [comment]
I did not experience this in Windows 10 x64.

**Comment by robb-price** [comment]
Works for Ubuntu 64 Bit.

**Comment by btfrise** [comment]
Works on Ubuntu 32bit.

**Comment by hcs0** [comment]
Works on Win 7x32
