### ISSUE TITLE
Stop and Restart Shortcuts not seen in Start menu option but is in Start Menu programs folder

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#264]
**How to recreate**
1. Finish installing Ver 3 test (2016.03.25.18.54)
2. Go to the Start menu option

**What happens**
Uninstall Rise Vision Player is in the Start menu options menu but not Stop and Restart Rise Vision Player.

When you right click on 'Uninstall Rise Vision Player' and choose 'Open File Location', it goes to where the shortcut resides (in Start Menu/Programs/Rise Vision).  The Start and Stop Rise Vision Player shortcuts are also there.

Uninstall Rise Vision Player shortcut URL is in /2016.xx.xx/Installer/scripts/uninstall.bat (this works)
Stop Rise Vision Player shortcut is 2016.xx.xx/Installer/scripts/background.jse stop.bat (this works)
Restart Rise Vision Player shortcut is 2016.xx.xx/Installer/scripts/background.jse start.bat (this works)

**What should happen**
User should see the Stop and Restart Rise Vision Player shortcuts

**Notes**
Occurred on Win 10 x64

**Comment by ahmedalsudani** [comment]
@hcs0 could not replicate this issue. My guess is it's a Windows issue out of our control -- possibly an out-of-date Start Menu cache.

@fjvallarino @tejohnso do you agree?

**Comment by fjvallarino** [comment]
@ahmedalsudani agreed. I have seen this in the past; it's not something we can control. After a restart the items should be displayed properly (restart usually not needed, of course).

**Comment by tejohnso** [comment]
@ahmedalsudani @fjvallarino This might be an issue with the jscript files.  It's highly coincidental that it's only happening to the Jscript links - it works with the .bat file link.   And after a reboot it's still not showing the jscript links in a search for "rise" in the start menu.  But if you go to All Apps and then scroll down to the Rise folder they're all there.

**Comment by ahmedalsudani** [comment]
@tejohnso did you manage to replicate it?

**Comment by tejohnso** [comment]
@ahmedalsudani It's happening in the SC instance hannah linked to in hipchat

**Comment by ahmedalsudani** [comment]
@tejohnso oh right. They do not appear when you search.

**Comment by ahmedalsudani** [comment]
@hcs0 we could not replicate this issue. We think we're ok to move on for now and see if this causes issues in the field. Is that ok with you?

FYI, @robb-price, @tejohnso
