### ISSUE TITLE
Rise Cache crashes

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#273]
**How to recreate**
1. Download the stable installer
2. Look into the folder directories under rvplayer

**What happens**
RiseCache crashes, and doesn't create the necessary folders

**What should happen**
RiseCache should create the cache and download folders in the RiseCache folder - and if the RiseCache folder doesn't exist it should create that as well. 

**Notes**
Also happens when testing out a new RiseCache.jar sent through for issue https://github.com/Rise-Vision/widget-video/issues/107
Seen on Win 7, 10.

**Comment by ByronDarlison** [comment]
@hcs0 @tejohnso @fjvallarino @ahmedalsudani @alanclayton @rodrigopavezi is this defect still open? Thanks

**Comment by hcs0** [comment]
I had a new .jar sent through that should fix this while testing, but when I install the stable Ver 3 I don't see /cache and /download folder under /RiseCache (after adding scheduled content).  Should this be in stable now or is it part of the new release?

@tejohnso @fjvallarino @ahmedalsudani

**Comment by fjvallarino** [comment]
@hcs0 @ByronDarlison @ahmedalsudani it's part of the release we will be sending to CS today

**Comment by btfrise** [comment]
This is fixed in Windows 10 x64

**Comment by ByronDarlison** [comment]
@hcs0 @btfrise @fjvallarino is this now confirmed fixed and can this be closed? Thanks

**Comment by hcs0** [comment]
@ByronDarlison Fixed on Win 7.
Haven't started on Linux yet (unless @btfrise has with x32)

**Comment by robb-price** [comment]
@btfrise @hcs0 @ByronDarlison This issue is verified and closed.
