### ISSUE TITLE
After adding a valid DisplayID, the Viewer does not recognize and apply it

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#276]
**How to recreate**
1. Install the test Electron .exe with the --rollout-pct=0 flag and confirm that you have the Electron browser
2. Do not select  "Add To Startup" checkbox 
3. Test with an invalid Display ID.  
4. Test with a valid Display ID.

**What happens**
When you add an invalid Display ID and press Apply, the viewer recognizes that it is invalid.  
When you add a valid Display ID and press Apply, the viewer does not provide any notices and is stuck on the spinning wheel.

**What should happen**
When adding a valid Display ID, the viewer should recognize that it is valid and applies the Display ID.

**Notes**
Win 7 x32 and x64, Linux 32/64, Win 10x64
Happens when the username has a space and doesn't have a space
Could not locate RiseDisplayNetwork.ini

**Comment by btfrise** [comment]
Same problem on Linux 32/64.

**Comment by robb-price** [comment]
@btfrise @hannah

After discussing with @tejohnso , the Electron installer requires a valid RiseDisplayNetworkII.ini file that contains a valid Display ID in it. Do not rely on entering one in during the install. Instead, you can copy one over, create a new one, whatever works better.

Can you confirm that it works as expected when a valid RiseDisplayNetworkII.ini file exists? If it does, we can close this.
