### ISSUE TITLE
Item Profiler not visible on Electron browser for Win7x32

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#277]
**How to recreate**
1. Install the test Electron .exe with the --rollout-pct=0 flag and confirm that you have the Electron browser
2. Do not select  "Add To Startup" checkbox 
3. Add DisplayID in RiseDisplayNetwork.ini
4. Schedule this presentation which uses the item profiler https://rva.risevision.com/#PRESENTATION_MANAGE/id=b94fcc96-f17c-4294-a637-5bbcf12a3e4e?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

**What happens**
The Item Profiler does not appear / works on Electron for Win 7x32.  

**What should happen**
Item Profiler to appear on Win 7x32

**Notes**
Win 7 x32 only, not Win 7 x64

**Comment by tejohnso** [comment]
@hcs0 does your note mean that it's only failing on win732 or it was only tested on win732?   I just tried it on lnx64 and it seems ok.  I used the presentation preview
bit.ly/1MQG7a7

**Comment by hcs0** [comment]
@tejohnso I am trying on Win x32 on the dev wall and can see the Item Profiler, seems to be an issue with my machine.  I don't know what it is though (maybe if I can run Dev Tools I can get more info as to why).  I'll close this issue.

**Comment by tejohnso** [comment]
OK @hcs0  Thanks.   Is it in a VM on your machine?  We've had multiple issues with VMs before.

**Comment by hcs0** [comment]
@tejohnso No, it's a win 7x32 box - it's on SC under Win 7 x32
