### ISSUE TITLE
Custom presentation does not work on Electron but works on Chrome

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#278]
**How to recreate**
1. Install Player with the Electron Browser, and schedule this Presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=adbcf629-3904-4cab-949b-05f8de6cfd0e?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55 (contains Image/Text Items) or this Presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=c7902181-fb1c-46b4-a7f2-90c85054a865?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55 (contains Image/Text Widgets)

Notice that the content issues occur in the screenshots below (Overlapping content and text):

![georgetownunittext](https://cloud.githubusercontent.com/assets/5868781/14317425/30cc4540-fbd6-11e5-8636-b5149bf0bdda.png)
![georgetownunittext2](https://cloud.githubusercontent.com/assets/5868781/14317532/b468d274-fbd6-11e5-9b6d-032cc2ea5bb0.png)

**What should happen**
The Presentation content should not appear all at once, and instead only appear when you interact with the Presentation. it should act the same way it does with the existing Player.

This same presentation was tested on the stable Ver 3 installer based on Chrome and no layout issues.  See screenshot below:

![georgetownuni-ver3stable](https://cloud.githubusercontent.com/assets/5868781/14318090/48c8e506-fbd9-11e5-9114-4cf6ecf40122.png)

**Comment by ahmedalsudani** [comment]
Thanks for the report, @hcs0. Which machines was this issue observed on?

**Comment by tejohnso** [comment]
![georgetown](https://cloud.githubusercontent.com/assets/1511535/14320935/0f4def72-fbe5-11e5-8c63-47d618712b38.png)

Fails directly in Chromium49 as well.

**Comment by hcs0** [comment]
@ahmedalsudani Win and Linux, also noticed by @btfrise.  If you need SC access it's at HANNAH Win 7 x64

@ahmedalsudani @tejohnso Issue updated with another presentation link containing Text/Image Widgets and seeing no improvements.

**Comment by tejohnso** [comment]
@hcs0 I don't see the other presentation with text/image wiget.

**Comment by tejohnso** [comment]
@hcs0 This is happening because the presentation relies on a flash video to trigger layout updates.  We don't support flash, and it's not present in chromium, hence the failure.  I think this can be closed.

**Comment by hcs0** [comment]
@alanclayton Do you know if other templates are using this flash video trigger for the custom presentations? Or should all have been phased out?

**Comment by alanclayton** [comment]
@hcs0 i'm not aware of others. @mmeiers can you review and let us know of similar presentations using triggers from the Vimeo Gadget? Was this type of configuration common? 

@sheadarlison FYI.

**Comment by hcs0** [comment]
@alanclayton I was thinking that we should get a list of these and test.  Or even test all custom layouts just to be sure (I don't know how many there are..)

**Comment by mmeiers** [comment]
@alanclayton @hcs0 @robb-price Yes once we got rid of the youtube widget David and the other designers move to vimeo. I don't know how many were built like this but it was common up until we started using video widget.

**Comment by ByronDarlison** [comment]
@alanclayton @robb-price @tejohnso @mmeiers @sheadarlison let's review and confirm the plan, or no plan, at scrum of scrums this morning. Thanks
