### ISSUE TITLE
DPI scaling is adjustable, and does not revert to 100% when Rise Player is started.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#288]
**How to recreate**
1. Install Rise Player 2016.04.11.15.45
2. Close player
3. Right click desktop, click display settings
4. Slide the "Change the size of text, apps, and other items:" to 150%

**What happens**
The windows desktop enlarges to coordinate with display scaling. HKEY_CURRENT_USER\Control Panel\Desktop\LogPixels has a hex value of 60.

**What should happen**
The windows desktop should remain at 100% display scaling. HKEY_CURRENT_USER\Control Panel\Desktop\LogPixels should have a hex value of 96.

**Notes**
Fresh install from 2016.04.11.15.45 installer
Windows 10 x64

**Comment by ByronDarlison** [comment]
@btfrise I am not sure that I follow this defect. If the user specifically changes the scaling on the device why do you think we should ignore that? Or am I missing something here? @ahmedalsudani @fjvallarino @robb-price @alanclayton anything to add to clarify this? Thanks

**Comment by ahmedalsudani** [comment]
@btfrise @ByronDarlison if the replication steps are exactly as described above, I do not see this as an issue. 

We only set the DPI setting when the Installer is launched and do not prevent the user from changing the value. After you run the installer, is it set to 100%, @btfrise?

Note: it has to be a complete run. i.e. you click continue until the window closes

**Comment by ByronDarlison** [comment]
@ahmedalsudani I tend to agree. @btfrise can you get back to us on this and also confirm if this is an issue whether or not it has to be fixed for this release?

**Comment by btfrise** [comment]
@ahmedalsudani That is correct, after installation completes it is set to 100%.

@ahmedalsudani @ByronDarlison This is not an issue if this is how it is supposed to function. The instructions provided to us in the testing doc state "(Windows only) Verify DPI scaling is fixed to 100% and won't move to 150%", which insinuates that the user should not be able to change the Display Scaling after Rise Player has been installed.

**Comment by ahmedalsudani** [comment]
@btfrise ah I see. Thanks for the clarification.

Sorry about the language in the testing doc. It does give the wrong impression about the expected behavior. 

Are you ok with me closing this issue?

**Comment by btfrise** [comment]
@ahmedalsudani You can close this one, although we do still have a defect related to display scaling. I will be logging it now that I have a better understanding of the function. Thanks.

**Comment by ahmedalsudani** [comment]
@btfrise ok, thanks.
