### ISSUE TITLE
Installer does not set Windows DPI scaling to 100% by default.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#289]
**How to recreate**
1. Set windows DPI Scaling to 150%
2. Install Rise Player using installer 2016.04.11.15.45

**What happens**
Windows DPI scaling remains at 150%.

**What should happen**
Windows DPI Scaling should be set to 100%.

**Notes**
It looks like another registry key needs to be modified in addition to LogPixels. I had success by changing HKEY_CURRENT_USER\Control Panel\Desktop\Win8DpiScaling to 1, see [this article](http://www.windows10update.com/2015/05/windows-10-tutorials-79-change-dpi-scaling-level-for-displays/).

This is not a regression, I believe a fix can wait for a future release.

**Comment by ByronDarlison** [comment]
@btfrise I don't follow the above. If Windows DPI scaling is set to to 100% and it should be set to 100%, as per above, what is the issue?

**Comment by btfrise** [comment]
@ByronDarlison There was a typo, I've corrected it. It remains at 150%.

**Comment by ByronDarlison** [comment]
@btfrise okay. But if the user has specifically set it to 150%, the system hasn't auto adjusted, why should we be changing it?

**Comment by ahmedalsudani** [comment]
Thanks @btfrise. We'll look into the suggested fix.

@ByronDarlison we don't have a way for knowing the user set it manually, so we set it to 100% in all cases

**Comment by ByronDarlison** [comment]
@ahmedalsudani sorry, now I am really confused. If the user sets it manually to 150% as per above, then according to the revised description it stays at 150%. We don't change it to 100%. And in either case, if the user has set it, why change it? This isn't an auto correction on start up, they set it on purpose one would think.

**Comment by ahmedalsudani** [comment]
@ByronDarlison Windows 10 automatically sets the DPI scaling factor based on the monitor it's attached to. The number of users who manually change DPI is very small.

Here's a comment @tejohnso left a on the [associated card](https://trello.com/c/9lI7Snos/1052-prevent-windows-10-reverting-from-100-to-150-magnification-1):

>This happens when a media player is moved from one display to another. Windows 10 recognizes the new display, and goes to it's default setting of 150% zoom. I don't think this is a huge problem, how many people are actively moving media players from one display to another? We could solve this by having the installer set the zoom to 100% each time it loads, but that would be something to bring up with delivery.

>To change Display Scaling: - Right click the desktop
- Click Display Settings
- Change the slider under "Change the size of Text, Apps, and other Items" to 100%

**Comment by ahmedalsudani** [comment]
Sorry, small correction. @btfrise left the comment above

**Comment by btfrise** [comment]
This is corrected in installer version 2016.04.15.14.56. Closing this issue.
