### ISSUE TITLE
Able to finish Ver 3 installer with CAP already installed

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#301]
**How to recreate**
1. Install Rise Chrome App Player
2. Install the test Ver 3 installer and run with the unattended flag

**What happens**
The CAP installed message flashes but the installation finishes. The user is able to finish installing and add their DisplayID.

**What should happen**
User should not be able to finish installing when CAP is installed.

**Notes**
Occurred on Win 7 x32

**Comment by ByronDarlison** [comment]
@hcs0 not sure I follow. Why would someone be installing in unattended mode and if unattended why wouldn't we complete the installation?

**Comment by hcs0** [comment]
@ByronDarlison If CAP is on the Display, the user can't resume with the installation.  I don't know what the unattended flag does (or why it's there) but it's on the testing spreadsheet for CS.  

The way I've tested it was:
1. Install CAP to confirm that you see the CAP message
2. (I forgot to uninstall CAP) Tested the --unattended flag, saw the CAP message but was surprised that I could finish the install.

**Comment by ByronDarlison** [comment]
@hcs0 to confirm, if you don't use the unattended flag then the user can't proceed with the install in this case. Is that right?

**Comment by hcs0** [comment]
@ByronDarlison Users don't use that flag.  But I don't know which part of the install process this flag is used for though.

But if you don't use the unattended flag you will see that CAP-detected message and that you can't finish the installation until CAP is uninstalled.

**Comment by ByronDarlison** [comment]
@hcs0 given this I don't think we have a bug. @tejohnso do you concur? Thanks

**Comment by tejohnso** [comment]
@ByronDarlison @hcs0 Yes, we don't halt the process in unattended mode if the install can continue.  It should only halt in attended mode when we know a user is there to react to it.  @hcs0 Can you let me know which line number this is on the spreadsheet?  I'll update it.  And I think this can be closed.

**Comment by hcs0** [comment]
@tejohnso Ok.  This is on the correct order in the spreadsheet (unattended first, then CAP).  I'll close the issue now
