### ISSUE TITLE
When the username has a space, Player starts after a reboot even after unchecking "Add to Startup"

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#304]
**How to recreate**
Using an account that has a space in the username, finish the Ver 3 installer testing with 0 rollout and uncheck "Add to Startup". Add the Display ID and reboot the Display.

**What happens**
After the Display reboots, the Player also starts again even after unchecking "Add to Startup".
There is no Rise Vision shortcut in the Startup folder.

**What should happen**
After unchecking "Add to Startup", Player should not start after rebooting the Display.

**Notes**
Occurred on Win 7 x64
There is a name space in the test account ('Rise Rise')

**Comment by ahmedalsudani** [comment]
@hcs0 does this only occur when there's a space in the username?

**Comment by tejohnso** [comment]
@hcs0 You mention there's no Rise Vision shortcut in the Startup folder which should be all that's necessary to ensure the player doesn't start after reboot.  I couldn't replicate this on win7 or win10.  Any ideas why it's starting event without the shortcut?

**Comment by hcs0** [comment]
@tejohnso @ahmedalsudani I did another test on a Win 7 machine without a username space and it works.  The test machine with this bug had a namespace on it (Rise Rise).  Could that be it?

**Comment by robb-price** [comment]
@hcs0 @tejohnso I updated the bug description to be clearer that this only happens when there is a space in the username.

**Comment by hcs0** [comment]
Could not recreate on Linux x64

**Comment by hcs0** [comment]
Resolved Win 7 and Win 10
