### ISSUE TITLE
Interactions with player are extremely sluggish.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#305]
**How to recreate**
1. Download http://install-versions.risevision.com/2016.04.20.21.28/installer-win-64.exe
2. Open a command prompt, and navigate to your downloads folder
3. type installer-win-64.exe --rollout-pct=0
4. Complete installation

**What happens**
Any interactivity with player takes over 15 seconds to complete. If I click quit, nothing happens for 15+ seconds. If I open explorer, access the start menu, and click Close Rise Player, or Restart Rise Player, these actions don't take place for 15+ seconds.

**What should happen**
Interactions with player should be immediate.

**Notes**
I tested this on two separate Windows 10 x64 NUCs. One with an i3 processor, one with an i5 processor.
@hcs0 mentioned that she did not replicate this on Windows 7.

**Comment by robb-price** [comment]
@btfrise Do you have a video of this in action? Also, does this happen on the existing player with the same content?

**Comment by hcs0** [comment]
Could not recreate on Linux x64

**Comment by btfrise** [comment]
@robb-price I do not, but @ahmedalsudani confirmed earlier that this player is quite a bit slower than the last release.

There is no content at the time of this test. This is just after an initial install.

**Comment by btfrise** [comment]
Recreated on Linux 32bit. It's still sluggish, but not as slow as Windows 10 64.

**Comment by ByronDarlison** [comment]
@btfrise is this only happening if you use the pct=0 option or can it happen without it as well? And, in your opinion, how often does this happen? Thanks

**Comment by btfrise** [comment]
@ByronDarlison If the installer is run without the pct=0 option, then the installer will download the production version of player. This was happening every time I launched the new installer.

**Comment by btfrise** [comment]
@ByronDarlison @tejohnso To clarify, "this was happening every time I launched the new installer" was poorly worded. I was seeing sluggishness every time I used the new installer, I was not seeing a production download and install each time.

**Comment by hcs0** [comment]
Did not observe this on Win 7x32/x64 and Win 10x64

**Comment by btfrise** [comment]
Resolved on Windows 10 x64.
