### ISSUE TITLE
On Windows 10, adding a Display ID causes Rise Player to quit and not reopen.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#306]
**How to recreate**
1. Download http://install-versions.risevision.com/2016.04.20.21.28/installer-win-64.exe
2. Open a command prompt and run installer-win-64.exe --rollout-pct=0
3. Complete player install
4. Input a display ID and click apply

**What happens**
After around 15 seconds, rise player closes and does not reopen.

**What should happen**
Rise Player should close, and reopen displaying the schedule assigned to that display ID.

**Notes**
I recreated this on two separate Windows 10 x64 machines, one i3 and one i5 NUC.
If I run the installer command again, it will open player and display schedule.

**Comment by hcs0** [comment]
@btfrise Was not able to replicate this on Win 7 x32 x64

**Comment by robb-price** [comment]
@btfrise Can you recreate on Linux?

**Comment by hcs0** [comment]
Could not recreate on Linux x64

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 can't recreate it on Win 64 or Lnx 64

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 are you ok with closing this issue?

**Comment by btfrise** [comment]
@fjvallarino I am not okay with closing this issue. I have now replicated on a third device, all three of these devices are sold in store.

Can you test on https://connect.risevision.com/Host#*Rise%20KC%20Office//55b1ccb0-7158-440c-85f0-5149c9137260 48" content cart? I will uninstall and prep it for your testing.

**Comment by hcs0** [comment]
Did not observe this on Win 7x32/x64 and Win 10x64

**Comment by btfrise** [comment]
Resolved on Windows 10 x64.
