### ISSUE TITLE
Not able to run Flash content after copying pepflashplayer.dll to rvplayer

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#307]
**How to recreate**
1. Complete the Ver 3 installer with 0 rollout and add a presentation containing Flash content.
2. Copy pepflashplayer.dll from Program Files (X86)/google/chrome/Application/Version Number/PepperFlash to …/rvplayer
3. Restart installer and run a Presentation with Flash Content included

**What happens**
Flash content does not play after copying the .dll and restarting the installer

**What should happen**
Flash content to play after running with the Flash testing instructions

**Notes**
Observed on Win 7 x64, but not Win 7 x32. On Win 7 x32, the Flash test was done after doing the upgrade test.
Account has a namespace ('Rise Rise').  On Win 7 x32, the account also has a namespace.
Did other variations of the test (run installer.exe from Installer folder, add DLL in other locations). 
DLL was from the latest Chrome downloaded today (April 21)

**Comment by hcs0** [comment]
After going through the **How to recreate** steps, I was able to get Flash to work on Win 7 x32 testing.
This was after doing the upgrade test from Ver 3 current to the test installer

Account has a namespace.

**Comment by tejohnso** [comment]
@hcs0 Can you double check the bitness of the dll file?  If it worked on x32 but not x64 that's the most likely cause.

**Comment by btfrise** [comment]
I was unable to recreate this on Win 10 x64.

**Comment by hcs0** [comment]
Not an bug
