### ISSUE TITLE
On Win 10 64, pressing "Restart Player" on displays app closes player and does not restart.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#308]
**How to recreate**
1. Download http://install-versions.risevision.com/2016.04.20.21.28/installer-win-64.exe
2. Open a command prompt and run installer-win-64.exe --rollout-pct=0
3. Continue player installation
4. Assign a display ID and click apply
5. Player does not reopen see defect #306 open a command prompt and run http://install-versions.risevision.com/2016.04.20.21.28/installer-win-64.exe
6. Once player is running with the assigned display ID, navigate to displays.risevision.com
7. Select the display
8. Click "Restart player"

**What happens**
Player closes after a short period of time (~15 seconds) and does not restart.

**What should happen**
Player should close and restart.

**Notes**
This was replicated on three separate Windows 10 x64 NUCs.

**Comment by hcs0** [comment]
Could not recreate on Win 7 x32 x64

**Comment by robb-price** [comment]
@btfrise Can we recreate this on Linux?

**Comment by hcs0** [comment]
Could not recreate on Linux x64

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 can't recreate it on Win 64 or Lnx 64

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 are you ok with closing this issue?

**Comment by ByronDarlison** [comment]
@btfrise @robb-price @hcs0 any conclusions?

**Comment by btfrise** [comment]
@ByronDarlison @fjvallarino I did recreate this on a third Windows 10 x64 NUC. I also took @fjvallarino through what is happening on defect #306 I would think that these two bugs are related. Francisco now has SC access to one of the NUCs displaying this behaviour Francisco, you should be able to replicate this bug on that SC NUC as well.

For posterity, this is not an issue on Linux 32.

**Comment by ByronDarlison** [comment]
@btfrise thanks. @fjvallarino given the above it doesn't sound like this blocked. ?

**Comment by fjvallarino** [comment]
@ByronDarlison I'll move it back to done. I put it on Blocked because I was not able to recreate it and I think Hannah was not able to recreate it either.

**Comment by ByronDarlison** [comment]
@fjvallarino did you mean done or the backlog? Not sure I follow? It isn't closed is it?

**Comment by fjvallarino** [comment]
@ByronDarlison I modified the message after clicking on "Comment". I meant "Doing", although it should be "Backlog" since I'm working on #306

**Comment by ByronDarlison** [comment]
@fjvallarino okay. Thanks

**Comment by hcs0** [comment]
Did not observe this on Win 7x32/x64 and Win 10x64

**Comment by btfrise** [comment]
Resolved on Windows 10 x64.
