### ISSUE TITLE
On Win 10 64 Bit, Player does not restart after starting installer w/--unattended flag and no network.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#309]
Sorry for the long title.

**How to recreate**
1. Download http://install-versions.risevision.com/2016.04.20.21.28/installer-win-64.exe
2. Disconnect network
3. Open a command prompt and run installer-win-64.exe --unattended
4. Complete installation, look for no network message
5. After no network message comes up, reconnect network

**What happens**
No network message stay on screen for 3 minutes. In the Windows taskbar "Restarting Rise Player" appears, and the no network message disappears. Rise Player does not restart.

**What should happen**
Rise Player should restart after 3 minutes when network is connected.

**Notes**
Tested on two separate Windows 10 x64 NUCs.

**Comment by hcs0** [comment]
Could not recreated on Win 7 x32 x64

**Comment by robb-price** [comment]
@btfrise Can we recreate on Linux?

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 can't recreate it on Win 64 or Lnx 64

**Comment by hcs0** [comment]
Could not recreate on Linux x64

**Comment by fjvallarino** [comment]
@btfrise @robb-price @hcs0 are you ok with closing this issue?

**Comment by ByronDarlison** [comment]
@btfrise @robb-price @hcs0 any conclusions?

**Comment by btfrise** [comment]
@ByronDarlison I believe this should be looked at with issues #306 & #308 as it is replicable on multiple machines.

**Comment by ByronDarlison** [comment]
@btfrise thanks. @fjvallarino do you concur this isn't blocked at this point?

**Comment by fjvallarino** [comment]
@ByronDarlison Yes

**Comment by hcs0** [comment]
Did not observe this on Win 7x32/x64 and Win 10x64

**Comment by btfrise** [comment]
Resolved on Windows 10 x64.
