### ISSUE TITLE
Running installer as root/sudo user creates rvplayer directory owned by root.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#311]
**How to recreate**
1. Download http://install-versions.risevision.com/2016.04.20.21.28/installer-lnx-32.sh
2. In a terminal, navigate to download folder and type chmod +x installer-lnx-32.sh
3. In a terminal type sudo ./installer-lnx-32.sh

**What happens**
Rise Player Uncompresses. Warning message about running rise player as root user displays, and installation is canceled. Trying again to run as an unprivileged user by typing ./installer-lnx-32.sh fails with the error message "Extraction failed".

Navigate back to home directory and type ls -l. You will see that the rvplayer directory exists and it is owned by root.

**What should happen**
Installation should check for installer running as a root user before extraction. If running as a root user, error message should display and terminate installation immediately. No rvplayer directory should be created.

**Notes**
Ubuntu 14.04 32bit
You can fix this by typing sudo chown -R computername.username /home/username. Further installs of Rise Player running as a non-privileged user succeed.

**Comment by hcs0** [comment]
Not able to recreate on Linux x64 
I delete any existing folders, enter root, attempt the installation and see the message against sudo.  I then exit and was able to finish the installation.

The rvplayer folder after this is in the rise group (not sudo)

**Comment by btfrise** [comment]
@hcs0 I was able to recreate this on my Ubuntu 14.04 64bit machine as well. Could you take a look at the video I created http://www.screencast.com/t/aZWalz98l and see if our processes differ at all? Thanks.

**Comment by hcs0** [comment]
@btfrise Thanks for the video! Yes we have different ways to get to sudo.  What I do is:

Run 'su'
Add the sudo password
I run chmod etc then I get the sudo message not to install.  I am not able to install.
To exit sudo I run 'exit'

I don't do sudo chmod etc

**Comment by btfrise** [comment]
Fixed on Linux 32bit.

**Comment by btfrise** [comment]
This is fixed on Linux 64bit. Closing defect.
