### ISSUE TITLE
Viewer running in Electron does not load insecure content

### ISSUE THREAD

**Issue by ahmedalsudani** [Rise-Vision/rise-launcher-electron#323]
Details on Trello

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/4631602551

**Comment by ByronDarlison** [comment]
To confirm this issue should now be closed right? Thanks

**Comment by ahmedalsudani** [comment]
@ByronDarlison yes, closing
