### ISSUE TITLE
After a reboot, the 'Extracting...' window appears and the Display restarts

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#326]
**How to recreate**
Finish installing Ver 3 and add the Display ID
Add to Startup Process and reboot the Display

**What happens**
The Player starts on reboot but the ‘Extracting…’ window appears above the presentation.  The presentation goes to a black screen and the presentation restarts.  It is observed to only restart once.

**What should happen**
The Player should restart without the ‘Extracting…’ window or the restart.

**Note**
Observed in Windows 10 x64

**Comment by ahmedalsudani** [comment]
@hcs0 that means an update was triggered. The "Extracting" dialog appears once downloading the production version completes.

I think there's a comment in the spreadsheet that says "Cancel the installation once it starts". The point behind that was to avoid triggering an update to production.

**Comment by hcs0** [comment]
I see, thanks! I'll close this issue now
