### ISSUE TITLE
Installing on Windows 32 with no network brings up the proxy page. 

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#380]
<b>How it works now:</b>
1. Run the 32 Bit Windows installer on a Display that is not connected to a network.
2. Notice that you get this screen: 
![2016-05-17_12-38-00](https://cloud.githubusercontent.com/assets/6862256/15330770/4847a040-1c2c-11e6-9963-769f4839424c.png)

<b>How it should work:</b>
The proxy scren should NOT show, the installation completes, and the no-network window is displayed.  After three minutes the installer should start again to retry in the event the network has returned

**Comment by tejohnso** [comment]
@robb-price The proxy screen should NOT show as you've stated.  But that's only in unattended mode.  If a user is present we give them the opportunity to fix things.

**Comment by robb-price** [comment]
@tejohnso As per line 17 in the spreadsheet: Confirm that the Proxy screen does not show, and the installation completes, and the no-network window is displayed.  After three minutes the installer should start again to retry in the event the network has returned

Sounds like that needs to be updated, right?
