### ISSUE TITLE
Windows 32: Running the installer Unattended with incorrect proxy information only shows a white screen

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#381]
<b>How it works now:</b>
1. Enter incorrect Proxy information into Internet Settings on the media player.
2. Run the installer using the unattended flag.
3. Once Player starts, and subsequent restarts, it sits on a blank white screen.

<b>How it should work:</b>
The Proxy screen should not show, the installation completes, and the no-network window is displayed.  After three minutes the installer should start again to retry in the event the network has returned.

**Comment by btfrise** [comment]
I'm seeing an issue with incorrect proxy information on Windows 10 x64 as well.

1. Enter incorrect Proxy information into Internet Nettings.
2. Run the installer using the unattended flag.
3. Player starts, goes to loading screen. Player tries to restart.

**Comment by tejohnso** [comment]
@btfrise @robb-price We don't do full proxy checking in unattended mode.  We skip it entirely because we don't want a proxy change to stop the player launch.    We only show the no-network window when there really is no network at all - as in the wireless interface is down.

**Comment by btfrise** [comment]
@tejohnso That doesn't match what line 18 of the testing sheet says.

"Confirm that the Proxy screen does not show, and the installation completes, and the no-network window is displayed.  After three minutes the installer should start again to retry in the event the network has returned."

**Comment by tejohnso** [comment]
@btfrise That's a mistake.  I'll update it.

**Comment by robb-price** [comment]
@tejohnso So the blank white screen or loading animation is what we expect to see?

**Comment by tejohnso** [comment]
@robb-price Yes, in that case player is going to let viewer do its best.  And viewer will end up in either of the above two situations you described if it can't get through.  We could prevent the viewer startup and show the no-network screen, but we could end up preventing an otherwise working display depending on how the proxy is configured.
