### ISSUE TITLE
Multiple instances of Viewer can be launched from Installer.

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-launcher-electron#395]
See screenshot here, http://www.screencast.com/t/rWv5ntXHN

**Comment by ahmedalsudani** [comment]
Thanks @alanclayton.

Was it the case that clicking "Start Player" would open a new viewer instance _every time_ you clicked, or did clicking it subsequently cause one of the windows to be killed and replaced?

We had an issue in the past where older versions of the Platform (Installer, Player, Viewer) were not killed by the new version, but this should be fixed as of release 13.

**Comment by ahmedalsudani** [comment]
@alanclayton welp. sorry, I misunderstood what you meant at first. This is a bug alright!

**Comment by ahmedalsudani** [comment]
@alanclayton this should be fixed in the latest production build.

You can get it from http://install-versions.risevision.com/ or by running the Installer with the arguments
`-- --rollout-pct=100`

Can you please confirm it's fixed and close this issue if that's the case? Thanks

**Comment by alanclayton** [comment]
@robb-price can you queue this up for someone in CS to validate please?

Thanks

**Comment by robb-price** [comment]
@alanclayton Will do.

**Comment by hcs0** [comment]
Verified
