### ISSUE TITLE
A '#' in the username causes the Installer to only show a white UI screen

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#396]
**How to recreate**
Create a username with # in it
Run the new installer

**What happens**
After extracting, the installer only goes to show a white UI screen.  The user is not able to input the Display ID.

**Notes**
Recreated in Win 10 x64 NUC (first occurred on Win 10 x32 Intel Compute Stick)

**Comment by ahmedalsudani** [comment]
@hcs0 thanks.

Was this recreated on a machine other than the user's Compute Stick that I looked into?

**Comment by hcs0** [comment]
@ahmedalsudani recreated on win 10 x64 NUC

**Comment by tejohnso** [comment]
@hcs0 This should be corrected in production now.  Please verify.

**Comment by hcs0** [comment]
@tejohnso @ahmedalsudani Confirmed on production
