### ISSUE TITLE
Browser data is deleted every time Viewer is launched

### ISSUE THREAD

**Issue by ahmedalsudani** [Rise-Vision/rise-launcher-electron#400]
A user has reported losing login sessions between Player restarts, likely due to deleted cookies.

**Comment by tejohnso** [comment]
@ahmedalsudani how are we validating this correction and who is doing the validation?

**Comment by ahmedalsudani** [comment]
@tejohnso I'm not sure. It was an issue reported by a user. Should we forward this issue to CS and ask for confirmation logins are preserved?

**Comment by tejohnso** [comment]
@robb-price Should we validate this internally or reach out to the user to have them validate it?

**Comment by hcs0** [comment]
@tejohnso @ahmedalsudani 

I can’t recreate the issue on Linux and Windows after a restart and reboot.  See below for the steps that I've taken using a website that required a login:

1. Use the production version installer (—pct-rollout=100)
2. Use the Web Page Widget with interactivity enabled
3. Add a link that requires a login (i.e. pluralsight.com)
4. Log in
5. Restart the Player
Then
6. Reboot

#5 and #6 login is maintained.

**Comment by tejohnso** [comment]
Thanks @hcs0 - I'll close this in that case.
