### ISSUE TITLE
R13 w/Chromium 50 does not play video on some hardware.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#410]
**How to recreate**
1. Create a display, add the display ID to ASUS hardware.
2. Create a presentation using the Video Widget.
3. Add this presentation to a schedule assigned to the new display.

**What happens**
Rise Player will only show a blank white screen.

**What should happen**
Rise Player should show a video.

**Additional troubleshooting**
On the ASUS machine, I installed Chromium 50 and tested playing video (https://storage.googleapis.com/risemedialibrary-09965383-06dc-458e-8313-4b1ed2aee7da/Fireplace-Video/Fire-Water-720P.webm). The video did NOT play. I installed Chromium 51, and the video DID play.

If I roll back to a version of Rise Player using Chromium 49, videos play.

A customer box is available here https://connect.risevision.com/Host#*Unsorted//11fdcd2e-8053-5a84-e34c-9f2f01c051a3. This is an Asus UN42, but we have another report of a user using a chromebox modified to run Linux as well.

**Comment by ByronDarlison** [comment]
@btfrise @robb-price @tejohnso this is resolved by rolling back right? And if correct, can you please close. Thanks

**Comment by btfrise** [comment]
@ByronDarlison correct. Closing
