### ISSUE TITLE
Chromium instance crashes when you make a change to Display Distribution of the Schedule

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher-electron#414]
**How to recreate**
1. Install the newest version of Electron Player with Chromium 51(2016.06.09.18.44)
2. Make a change to the distribution of the Schedule this Display is currently in. Notice that Chromium will crash on the Display. 

Previously we were seeing this when you make any change to the Presentations in that Schedule, but that appears to be hit or miss in crashing Chromium. Changing the Display Distribution causes it 100% of the time.

**How it should work**
When the Display Distribution is modified, Chromium should not crash.

**Notes**
Appears on all flavors of Windows and Linux

**Comment by robb-price** [comment]
@tejohnso Just an FYI, we tried the exact same steps using the Uptime Schedule, and all Displays were fine. That makes us very confident this is tied to Chromium 51.

**Comment by ByronDarlison** [comment]
@robb-price @hcs0 @tejohnso with the roll back this is resolved now right? If so, please close. Thanks

**Comment by robb-price** [comment]
@ByronDarlison Yes, closing.
