### ISSUE TITLE
There is no internet connection error message when there is an internet connection.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#477]
**How to recreate**
1. In a new presentation in RVA, add a placeholder with a custom URL.
2. Add a broken URL to that custom URL placeholder (i.e. http://tippie.uiowa.edu/tippieview/center/marketwall/icontext_henryheader.html)
3. Publish and assign to a display

**What happens**
When Rise Player loads, it will show a "There is no internet connection" screen.

**What should happen**
1. Player should load the rest of the presentation without the broken URL
2. Player should serve a more descriptive message "http://tippie.uiowa.edu/tippieview/center/marketwall/icontext_henryheader.html is returning a 404, please check your presentation settings and publish again"

Sample presentation at https://goo.gl/kgniaF
We are seeing older RVA users upgrade their players recently, which has brought this to my attention.

**Comment by tejohnso** [comment]
@btfrise over to you for confirmation and close.

**Comment by btfrise** [comment]
@tejohnso Looks good! Thanks!
