### ISSUE TITLE
Player should not start if Display Id does not exist

### ISSUE THREAD

**Issue by fjvallarino** [Rise-Vision/rise-launcher-electron#480]
Unattended mode does not validate if Display Id was set up, which leads to launching Viewer in an invalid state. It should display the Configuration screen and not start Viewer in that scenario.

**Comment by fjvallarino** [comment]
@btfrise these installers do not launch Viewer if Display Id is not set. The user will be sent to the config screen in that scenario

https://circleci.com/gh/Rise-Vision/rise-launcher-electron/1972

@tejohnso FYI

**Comment by btfrise** [comment]
@fjvallarino @tejohnso Fix tested and looks good. The Book PC has a hold on 40 media players until we can update their image with this fix.

**Comment by tejohnso** [comment]
@btfrise Can we close this now?

**Comment by btfrise** [comment]
@tejohnso Yep, this can be closed.
