### ISSUE TITLE
Heartbeat status incorrect

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-launcher-electron#483]
Viewer: 2-00-201609292007
Player: RisePlayerElectron 2016.09.30.17.41
Display: PMPRUBNMRCXE, PKZJRKHH8QM3, 89YMNGW3J8SE, more if needed. 

Player is running, I can update content, restart player, but heartbeat status shows offline, and connection timestamp is stale.

Issue is not present on v1 or v2 player.

**Comment by fjvallarino** [comment]
@alanclayton this needs changes on the Apps side, which should load the information from a different location (the messaging service)

**Comment by tejohnso** [comment]
@alanclayton Can we close this now since it was specific to a staging version of player? We cards on apps / delivery boards to address the issue.

**Comment by alanclayton** [comment]
@tejohnso Okay re: closing. Thanks
