### ISSUE TITLE
Geolocation Permissions are not being granted as expected

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#584]
<b>How it works now:</b>
Use the Digichief Weather Widget in a Presentation, using Geolocation. Notice that when you preview the Presentation with HTTP, you do not see the Widget in preview, if you change the preview URL to HTTPS, you get requested to allow Geolocation:
<img width="638" alt="screen shot 2017-07-13 at 2 55 49 pm" src="https://user-images.githubusercontent.com/6862256/28186406-04f5b0ac-67e9-11e7-9596-769f7bb369a7.png">

If you chose to <b>Block</b> Geolocation, you see the message "Unable to obtain geolocation position." in the Dev Console.

When you run this Presentation on a Display, you get the exact same message as if you had pressed Block. In the Console, you see "Unable to obtain geolocation position."

Presentation to use: https://apps.risevision.com/editor/workspace/3f597b3a-82cf-4c8f-a638-7181fedcfec2/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

<b>How it should work:</b>
Electron should implicitly grant the Geolocation permission. instead it shows nothing in the Presentation, and the "Unable to obtain geolocation position." appears in the console.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Digichief Geolocation Weather Widget](https://trello.com/c/9lPYkMSN/4510-2-digichief-geolocation-weather-widget)

**Comment by rodrigopavezi** [comment]
@robb-price the problem is that our player uses a custom built of chromium which has a geo location google api key with limited number of requests. So for now we suggest users to enter their location on the widget settings. cheers
