### ISSUE TITLE
2017.08.03.16.42 does not complete install on certain Media Players. Asks for Proxy settings when no proxy is present.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#595]
When installing from the newest installer on certain users Media Players, the installer asks for proxy settings even when there is no proxy present.

User 1: Running on Raspberry Pi. User installed another Pi on same network with absolutely no problem. 
https://connect.risevision.com/Host#Access/Blake%20Freeman//d0a5e1de-85df-3a96-dd1f-a661fce65918

User 2: Users current version is stuck on 2017.07.04 release. When adding the flag -- --release-pct=100, installer attempts to update and gets blocked at the proxy screen. When installing from newest installer, it also gets blocked at proxy screen. When run from currently installed 2017.07.04 release, Rise Player runs. There is a Calendar issue that could be related to this older player version.
https://connect.risevision.com/Host#Access/All%20Machines/berkshire/e7af3e83-446f-ddf6-0ff0-a3ad8454d7b6

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Investigate possible installer issue.](https://trello.com/c/SLeI81fN/5143-2-investigate-possible-installer-issue)

**Comment by tejohnso** [comment]
This was happening because the installed `ca-certificates` library was a 2013 version.  
I added the Ubuntu [SECURITY] repository, upgraded `ca-certificates` and `libnss3`, and confirmed all is well.
