### ISSUE TITLE
Electron crashes when swiping a lot

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-launcher-electron#600]
**Presentation URL:**
https://apps.risevision.com/editor/workspace/2d9d1010-2ac7-47a9-b345-a30f2716db7b/?cid=bc0d6972-c5d7-4f3e-9eeb-3aa254aa424f

**Schedule URL:**
https://apps.risevision.com/schedules/details/974e581f-0c93-4354-b226-4291825747ec?cid=bc0d6972-c5d7-4f3e-9eeb-3aa254aa424f

**Display URL:**
https://apps.risevision.com/displays/details/457393CG2YKA?cid=bc0d6972-c5d7-4f3e-9eeb-3aa254aa424f

**Screen Connect URL if available:**
https://connect.risevision.com/Host#Access/*Rise%20KC%20Office//66342bca-50f0-4662-87e9-3efb61d1b3db

**What is not working/What is currently happening:**

- Go to the page with the profiles. 
- Touch and hold on the right side of the scroll bar (on right side). Then swipe left. 
- Do it multiple times.
- Electron will crash. 

**What is expected to work/What is the client expecting:**
Electron doesn't crash.

**What has been tried so far:**
Nothing yet

**Have you been able to replicate in preview:**
No 

**Have you *also* been able to replicate on a display:**
Yes, one of the dell touch screens and one of the samsung screens with an overlay

**Are there any photos or videos:**
Listen on mute, theres a lot of background noise
https://drive.google.com/a/risevision.com/file/d/0B-WhEeWXfRbgZ3M1QzFGYWlOZjQ/view?usp=sharing

**Comment by tejohnso** [comment]
@sheadarlison can you upload log files showing the crash?  If it's on that screen connect display, we can get it but we'd need to know roughly what timestamp to look for.

**Comment by sheadarlison** [comment]
@tejohnso It's on that display, would have been on August 23rd around 3:45PM.

**Comment by tejohnso** [comment]
@sheadarlison can this be closed?
