### ISSUE TITLE
False Positive Network Test on Older 14.04.01

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-launcher-electron#609]
**The issue**
In some cases using older packages (we've seen this on 12.10 and 14.04.01) The installer for Player v3 will show false positives on the network check. When we continue the installation viewer never fully loads and spins forever.

The only fix we know of is to upgrade to latest version of 14.04 (14.04.05). After this there are no false positives, and the player/viewer load just fine. This is done by enabling updates in the settings and running "sudo apt-get update && sudo apt-get upgrade"

**So far unable to re-create**
We are so far unable to fully re-create this bug, mostly due to the fact that it's hard to find 14.04.01 installs. 

attached is an image of the false positive. Unfortunately it doesn't show much as it just looks like a failed network test, but this clients network is fine (many other displays working on the same network, running newest player). They are also running 14.04.01.

![untitled](https://user-images.githubusercontent.com/27289926/30663013-5b3d6268-9e06-11e7-978e-47c9a19701bb.png)

**Comment by alanclayton** [comment]
Caused by out dated certificate libraries. Solution is to update linux version
