### ISSUE TITLE
When some Windows Displays restart, they are sitting on a white screen until Player is restarted.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#671]
<b>How it works now:</b>
Users are reporting that when a Display restarts, it sits on a blank white screen, despite having content scheduled to play. When you restart the device, it will begin playing the correct Presentation.

There doesn't appear to be any rhyme or reason, outside of a majority, but not all of the media players are older. In the case of Bentley, they are OPS boxes. So far we have not gotten reports of it happening on Linux, but that may change.

We have not been able to recreate this internally, but you can see via Screenconnect on the Bentley devices when it occurs.

These Displays are reporting the issue:

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Investigating If we have a media player issue re: white screens](https://trello.com/c/fSZ5ICRs/7067-3-investigating-if-we-have-a-media-player-issue-re-white-screens)

**Comment by tejohnso** [comment]
@robb-price closing for now
