### ISSUE TITLE
Installer hangs during extraction.

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-launcher-electron#683]
Reported here: https://help.risevision.com/hc/en-us/community/posts/360000680983-extracting-local-messaging?page=1#community_comment_360000188906

- Operating System Version: we've seen it mainly on all windows platforms, but also in raspbian.
- Player Version: all
- Viewer Version: -

##### What is the expected behavior?
Installer extracts swiftly

##### What is the actual behavior?
Installer hangs while extracting.

##### What steps can be taken to replicate the problem? 

1. Install, run and stop a current version of installer.
2. install a version of installer from one or months below without uninstalling current version
3. stop but not uninstall
4. install again a new version of installer.

**Comment by robb-price** [comment]
@santiagonoguez Do you have a previous version of the installer that I can use for step 2?

**Comment by santiagonoguez** [comment]
Hi Robb,

I used this one:

https://console.cloud.google.com/storage/browser/install-
versions.risevision.com/backups/2018.01.03.17.33/?
project=avid-life-623&prefix=i

But I learned there's another thing to keep in mind with these tests. We
currently have a limit to the upgrades for modules of a display per day. If
you're not seeing the issue being reproduced, you can try deleting a file
called upgrade-attempts.json from the rvplayer directory before restarting
/ reinstalling. This will reset the upgrade limit for the current day.

Please contact me if you have more questions about this !

**Comment by santiagonoguez** [comment]
Additionally, I didn't confirm this but I believe you could also reproduce
going back to beta, then back again to stable:    stable -> beta -> stable

I think I couldn't reproduce initially the problem using this approach
because I hadn't considered the upgrade limit problem at the time !!!

**Comment by santiagonoguez** [comment]
Fix has gone to stable branch, starting with player version 2018.03.06.17.52. 

Gradual upgrades should fix the problem with already installed installers also. Closing this issue.

**Comment by robb-price** [comment]
Confirmed working on Windows 64 and Linux 32. Thanks!
