### ISSUE TITLE
Display is showing offline when it is really online

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#690]
- Operating System Version: Windows 7 32 / Windows 64
- Player Version: RisePlayerElectron 2018.03.14.14.39 Standard / Professional
- Viewer Version: 2-01-201803191806

##### What is the expected behavior?
Displays are showing as Offline in RVA, but are actually online when the user looks at the Display. One similarity we have seen with several of these Displays, is that they appear to all be using WiFi for their network connection. Not all, but most.

##### What is the actual behavior?
Display is online and running a Presentation.

##### What steps can be taken to replicate the problem? 
So far we have not been able to replicate internally, but we have gotten screenconnect and logmein access to some Displays reporting the issue.

**Comment by tejohnso** [comment]
[Active Trello card](https://trello.com/c/biflRsQ0)

**Comment by alanclayton** [comment]
@tejohnso @robb-price I believe this issue is now resolved. If confirm and close this defect if my understanding is correct.

**Comment by robb-price** [comment]
Confirmed.
