### ISSUE TITLE
Display logs show a loop of installing/running previous Player and newest Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#693]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Linux (and one Windows machine)
- Player Version: 03.14.14.39 and 2018.04.02.17.29
- Viewer Version: 2-01-201804051422

##### What is the expected behavior?
When the Display upgrades, all logs on the Display and in Big Query report the appropriate running version in case of any issues.

##### What is the actual behavior?
It appears that the Display is crashing and being restarted by the watchdog, however this needs to be confirmed, and when it starts up again, the Display and BQ logs are reporting that it is running the previous version of the installer.

##### What steps can be taken to replicate the problem? 

View the logs for the Display ID's listed in the Trello ticket.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Do we have an issue with Displays going to desktop on updates?](https://trello.com/c/8lrBh9R4/7758-3-do-we-have-an-issue-with-displays-going-to-desktop-on-updates)

**Comment by santiagonoguez** [comment]
Just to clarify, as Stu said in the chat the two versions that appear does not refer to a new and old version of the player, but to the version of the player and the launcher modules that both log to the same table. The real problem here is the display crashing.
