### ISSUE TITLE
Previous module versions not removed from /rvplayer

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-launcher-electron#697]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: All
- Player Version: 
- Viewer Version: n/a

##### What is the expected behavior?
When a Player Module is upgrade to a newer version the previous version should be purged from disk. Any unused files/folders in /rvplayer should be removed. 

##### What is the actual behavior?
Previous module versions are not being removed https://www.screencast.com/t/XcK8ktTWKku9. 

##### What steps can be taken to replicate the problem? 
I was NOT able to replicate upgrading from 2018.03.14.14.39 to 2018.04.10.14.22. During the upgrade, I saw [two versions](https://www.screencast.com/t/zdHDHJBqT1X) of launcher module in /rvplayer/modules/launcher, but the previous version 2018.03.14.14.39 was [removed](https://www.screencast.com/t/HgvkbySvt) after content started, but it is clear that there is a problem given what is described under the actual behavior above.

**Comment by stulees** [comment]
@alanclayton @santiagonoguez We are at 100% in our current release which resolves this issue. I think we can close, agreed?

**Comment by santiagonoguez** [comment]
I agree
