### ISSUE TITLE
Windows updates preventing rise user sign in on next boot

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#699]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version:  Windows 10
- Player Version: N/A
- Viewer Version: N/A

##### What is the expected behavior?
After a Windows update, Windows should automatically login to the rise user and start Rise Player.

##### What is the actual behavior?
After a Windows update, Windows logged into a temporary profile and did not start Rise Player.

##### What steps can be taken to replicate the problem? 

1. I wasn't able to replicate it, but it's been showing up on a lot of client media players.

**Comment by santiagonoguez** [comment]
Couldn't be replicated after several days, we're closing this.
