### ISSUE TITLE
Trying to play files that are being throttled from Storage results in a 502 Bad Gateway Message on the Player and a "Problem Retrieving this file" message on the Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#700]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Windows 10
- Player Version: 2018.04.10.17.21
- Viewer Version: 2-01-201804091627

##### What is the expected behavior?
There should only be a message stating the specific issue (Your file is throttled, etc), not "There was a problem retrieving the file" on the Display.

##### What is the actual behavior?
The Display shows the message that it had a problem retrieving the file:
![2018-04-12_16-28-00](https://user-images.githubusercontent.com/6862256/38702382-86d080a0-3e6e-11e8-82cf-dee3aef5f699.png)

##### What steps can be taken to replicate the problem? 

<a href="https://apps.risevision.com/editor/workspace/28454a0e-b2af-4b9a-8fc9-04e3348ce84e/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">This Presentation</a> results in the issue listed above. Some of the content has been throttled, the others have been deleted, and that message shows correctly.

Screenconnect link will be added to the Trello Ticket.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Autism Center Bandwidth Usage Investigation](https://trello.com/c/Tn3Ut304/7802-3-autism-center-bandwidth-usage-investigation)

**Comment by stulees** [comment]
@robb-price If this is being considered a bug, it should go to Content and the bug logged against either the Image/Video widget as that is the content responsible for displaying that message.  Thanks @alanclayton @sheadarlison FYI

**Comment by robb-price** [comment]
@stulees I had mentioned it to @tejohnso and he recommended adding it here. @tejohnso is @stulees right? Shoudl I move it to the appropriate Widget repo?

**Comment by sheadarlison** [comment]
@robb-price why should no messages show?

**Comment by robb-price** [comment]
@sheadarlison Good point, it should be a message reflecting the specific issue. I have changed that above.

**Comment by sheadarlison** [comment]
@robb-price I still don't follow, is the problem what the message says or is the problem that the video won't play or is it both? And if it is what the message says what should the text be changed to? 

Thanks

**Comment by robb-price** [comment]
@sheadarlison Both. It won't play because it is throttled. But as a user, you have no idea what the problem is, since all it says is there was a problem retrieving the file. 

When the file is in the trash, the message tells you that it is in the trash, which is a clear indication of A) why it won't play, and b) what do to do correct it.

Does that help?

**Comment by ByronDarlison** [comment]
@sheadarlison why are we showing an error on the screen? Can you clarify that for me?

**Comment by sheadarlison** [comment]
Thanks @robb-price it does.

@ByronDarlison We've been showing those messages for a couple years now, I don't know what the thinking behind the decision was, it was made by @alanclayton. 

I would prefer not to pursue removing error messages on the displays until we pursue the epic to improve Image and Video Widgets.

**Comment by ByronDarlison** [comment]
@sheadarlison @alanclayton the principle has always been do not show errors on a display.  We should not be doing anything to on a display that conveys an error...

As to when we fix this, that is up to you, but before we talk about that, let's make sure we are in agreement about "how" this should be working. Thanks

**Comment by sheadarlison** [comment]
@ByronDarlison I agree that we shouldn't show error messages.

**Comment by ByronDarlison** [comment]
@sheadarlison okay. You have a defect. Figure out where it falls in your backlog. Thanks!

**Comment by robb-price** [comment]
@sheadarlison Will do. Thanks!
