### ISSUE TITLE
Viewer restarts

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#701]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Ubuntu 14.04
- Player Version: Any
- Viewer Version: Any

##### What is the expected behavior?
Viewer is stable

##### What is the actual behavior?
On some displays viewer restarts multiple times per day

##### What steps can be taken to replicate the problem? 

1. See previous discussions

**Comment by tejohnso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defect 701 - viewer restarts](https://trello.com/c/UbJS6qo8/4238-defect-701-crash-to-desktop)

**Comment by stulees** [comment]
@tejohnso This issue was isolated to Image Widget and handed over to Content. I think we can close, can you confirm?
