### ISSUE TITLE
Streaming video does not load in Rise Player

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#702]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Windows 10 / Ubuntu 16.04 / Raspbian Jessie
- Player Version: RisePlayerElectron 2018.04.10.17.21 Professional
- Viewer Version: 2-01-201804091627

##### What is the expected behavior?
HTML5 Live stream should autostart and play in Rise Player.

##### What is the actual behavior?
HTML5 Live stream does not autostart or play in Rise Player.

##### What steps can be taken to replicate the problem? 

1.Add a web page with an [HTML5 live stream](https://cedarfalls.viebit.com/player_live.php?hash=3666443c-3b31-4c25-b992-22b0f5193165) to a Schedule, either with the Web Page Widget, or the URL Item.
2. Update Display to show new content

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) rise-launcher-electron #702](https://trello.com/c/PWjjmklj/7820-1-rise-launcher-electron-702)

**Comment by btfrise** [comment]
iFrame websites are loaded sandboxed and disallow plugins. This is to restrict the iframe site from redirecting the host presentation.

**Comment by rudibravo** [comment]
@btfrise issue is fixed and rolled out to production. can you verify and fix? Thanks
