### ISSUE TITLE
Local Storage not providing Twitter Module with twitter.json

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-launcher-electron#717]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: 32-bit Microsoft Windows 10 Home
- Player Version: RisePlayerElectron 2018.05.10.14.30 Professional
- Viewer Version: 2-01-201804171855

##### What is the expected behavior?
Twitter Module get's twitter.json from local storage module 

##### What is the actual behavior?
Twitter Module is currently not getting twitter.json from local storage module and because of that it can't get tweets

**Comment by santiagonoguez** [comment]
After following it, it appears to be a Twitter bug, @rodrigopavezi is confirming it. We'll be closing this soon if that's the case. @sheadarlison @SpencerHawkswell @alanclayton FYI.
