### ISSUE TITLE
Displays showing offline

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#720]
https://risevision.zendesk.com/agent/tickets/22644

https://trello.com/c/xUEwkhOU/4288-3-ticket-22644-displays-showing-offline

**Comment by tejohnso** [comment]
@justinsmith1 @robb-price Can we close this one now?

**Comment by robb-price** [comment]
@tejohnso Yup, that works for me. I have gone ahead and closed it.
