### ISSUE TITLE
Service workers failing with rise player

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-launcher-electron#721]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Windows 10
- Player Version: 2018.05
- Viewer Version: not relevant, fails even when bypassing viewer

##### What is the expected behavior?

Whenever a page with service workers is loaded in a presentation, the service worker should register if it works well when invoked directly through a browser or a simple electron app.

##### What is the actual behavior?

- When the player is run in attended mode the service worker never registers
- When the player is run in unattended mode the service worker most of the time registers
- When the player runs automatically after reboot ( unattended mode ) the service worker never registers
- When the player is run directly, the service worker always registers: 
      LOAD_MODULE_IN_ELECTRON=player-electron
      installer.exe
- When the service worker is run and there is a remote manifest override, the service worker always registers ( though I’ve not tested this extensively ).
- When the service worker is loaded directly in electron ( no player ) but with player’s configuration, online detection, preload scripts, event handling, ipc configuration, the service worker always registers
- Changing electron version to 1.7. 1.8, or even 2.0 doesn’t help at all.
- It doesn’t matter if player runs the service worker page directly or through viewer.

##### What steps can be taken to replicate the problem? 

1. See video in description of https://trello.com/c/fX50vWRU/4283-3-offline-play-not-reliable-w-web-page

2. To replicate it bypassing viewer add viewerurl=https://site with service worker in RiseDisplayNetworkII.ini

**Comment by tejohnso** [comment]
@santiagonoguez Can we close this now?

**Comment by santiagonoguez** [comment]
@tejohnso I validated it working in Cambria's display, so I think it's safe to close it.
