### ISSUE TITLE
Corrupt Rise Cache Database is causing a Player to sit on File is Downloading

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#723]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: 64 Bit Ubuntu 14.04
- Player Version: RisePlayerElectron 2018.05.16.13.56 Standard
- Viewer Version: 2-01-201804171855

##### What is the expected behavior?
The Files should download as expected into the Cache.

##### What is the actual behavior?
Player is sitting on "File is Downloading" message, while the logs show this: 
![2018-05-22_15-47-00](https://user-images.githubusercontent.com/6862256/40390399-21185df2-5de3-11e8-9add-d515c89708a0.png)

##### What steps can be taken to replicate the problem? 
I've never seen this on another Display and so far can't replicate.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Users blocked] Issue 723: Corrupt Rise Cache Database is causing a Player to sit on File is Downloading](https://trello.com/c/X0yauQ5m/8025-3-users-blocked-issue-723-corrupt-rise-cache-database-is-causing-a-player-to-sit-on-file-is-downloading)

**Comment by tejohnso** [comment]
This is with content team

**Comment by sheadarlison** [comment]
@tejohnso it is with the Content team, but we can't open issues in the Rise Cache repo so either that should change or this should stay open here. Thanks

**Comment by btfrise** [comment]
Duplicate issue, closing. https://github.com/Rise-Vision/widget-video/issues/210
