### ISSUE TITLE
Rise Player won't show displays with old-style display ID's

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-launcher-electron#725]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version:Windows 7/10
- Player Version: RisePlayerElectron 2018.05.22.19.22 Professional
- Viewer Version: 2-01-201804171855

##### What is the expected behavior?
Both old-style and current display IDs work on Rise Player either way

##### What is the actual behavior?
Continually spinning on a grey screen

##### What steps can be taken to replicate the problem? 

1. Enter an old-style display ID into Rise Player -- it doesn't work
2. Enter a current display ID (even with same content) -- it works

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Old Display ID's don't work with new version of player](https://trello.com/c/sHmYt8Mx/8006-old-display-ids-dont-work-with-new-version-of-player)

**Comment by tejohnso** [comment]
@robb-price Can you confirm this issue is resolved / close the issue? It should be corrected as part of our latest release.

**Comment by robb-price** [comment]
@tejohnso This is working, as I tested and confirmed with this Player: https://apps.risevision.com/displays/details/8a14e0cd-6d7a-48a9-b253-ea7f0feb5cad?cid=f114ad26-949d-44b4-87e9-8528afc76ce4&cHJpb3JpdHktc3VwcG9ydA=1

Verified and Closed.
