### ISSUE TITLE
Windows Updates show on top of Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#726]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: Windows 10 32 & 64 Bit
- Player Version: All
- Viewer Version: All

##### What is the expected behavior?
Windows updates should be  behind Player.

##### What is the actual behavior?
Windows update notifications show on top of Player:
![windowsupdate](https://user-images.githubusercontent.com/6862256/40544815-88d498b4-5ff7-11e8-90b5-dcbbaac3fe86.JPG)

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Ticket Blocked] - Issue 726: Windows Updates show on top of Player](https://trello.com/c/O2OdACYw/8057-3-ticket-blocked-issue-726-windows-updates-show-on-top-of-player)

**Comment by tejohnso** [comment]
Closing as discussed in SoS. Please reopen on subsequent reports.
