### ISSUE TITLE
Unofficial Chrome App Player preventing easy installation of official Rise Player

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#728]
- Operating System Version: Ubuntu 16.04
- Player Version: Chrome App Player
- Viewer Version: N/A

##### What is the expected behavior?
The official installer should provide an option for automatically uninstalling Chrome App player on Windows and Linux. Some kind of popup that says something like this "Unofficial Chrome App Player detected. Would you like to uninstall the Unofficial Chrome App Player to complete the installation of Rise Player?". If the client selects yes to this prompt, the installer could manually delete the extension from the Chrome/Chromium extension folder as shown here: https://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions 

##### What is the actual behavior?
When launching the official installer when the Chrome App Player is installed, the installer asks the user to follow the steps uninstall the Chrome App Player first, then restart the installation.

##### What steps can be taken to replicate the problem? 
Attempt to install official Rise Player while the unofficial Chrome App Player is installed.

**Comment by rudibravo** [comment]
We updated the error screen and published a help center article to cover the uninstall with more details.
@robb-price @kaden-rise I will go ahead and close this issue.
@alanclayton FYI
