### ISSUE TITLE
Displays show "trashed" content

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#732]
### Problem
Displays will continue to show "trashed" content. 
When the user deletes a file in the Storage app it goes to the "Trash" folder there but Rise Local Storage doesn't delete the file locally. 

### HWMS
Trashed content is not shown on a presentation

**Comment by andrecardoso** [comment]
Local storage now sends the DELETE/ADD FILE-UPDATE message when files are trashed or restored. Widgets should use these messages to hide/show content accordingly.
