### ISSUE TITLE
If Windows user contains a bracket, Player will not install.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#740]
- Operating System Version: Windows 10 32 or 64 Bit
- Player Version: RisePlayerElectron 2018.06.13.15.13 Licensed
- Viewer Version: 2-01-201806011112
--
##### What is the expected behavior?
Player should install as expected, and then start up automatically.

##### What is the actual behavior?
Player extracts, and then closes immediately.

##### What steps can be taken to replicate the problem? 

1. Create a user on the machine with a bracket in the name, for example: Robb (Robb)
2. Log in as that user, download and attempt to install Player.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Ticket Blocked] - Issue 740: If Windows user contains a bracket, Player will not install](https://trello.com/c/Ftt19jtA/8146-3-ticket-blocked-issue-740-if-windows-user-contains-a-bracket-player-will-not-install)

**Comment by rudibravo** [comment]
@robb-price if you download the latest player, this should now be fixed. Can you please verify and close? Thanks

**Comment by robb-price** [comment]
@rudibravo Confirmed and Closed!
