### ISSUE TITLE
Local storage does not send NOEXIST message for trashed/deleted files

### ISSUE THREAD

**Issue by andrecardoso** [Rise-Vision/rise-launcher-electron#745]
##### What is the expected behavior?

Local storage module should send NOEXIST message when a watch is submitted to a file that got deleted or trashed on GCS

##### What is the actual behavior?

Local storage sends CURRENT when file was deleted.

Local storage sends the "File is trashed" message when file was trashed.

##### What steps can be taken to replicate the problem? 

1. Set up a presentation with a image widget referencing a File
1. Delete/trash the file while player is offline
1. Launch player
1. Observe local storage logs

**Comment by tejohnso** [comment]
@andrecardoso I think we can close this now?
