### ISSUE TITLE
Links to install Rise Player Linux and Raspbian shell scripts open in new tab instead of prompting to download.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#746]
- Operating System Version: Mac OS X 10.13.5
- Chrome Version: 67.0.3396.99 (Official Build) (64-bit)

##### What is the expected behavior?
Clicking a link to download a Linux or Raspbian installer should prompt for download.

##### What is the actual behavior?
Clicking a link to download a Linux or Raspbian installer opens a new tab with the contents of the script displayed.

##### What steps can be taken to replicate the problem? 

1. In Chrome go [here](https://help.risevision.com/hc/en-us/articles/115001872283-Install-Rise-Player-on-Linux) or create a new Display.
2. Click "Download Player for ..."

##### Notes
Cannot replicate in Firefox, or with other .sh files around the web. Test by clicking the ticketbleed.sh hyperlink [here](https://testssl.sh/).

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Rise Player downloads for Linux and Raspbian open in new tab instead of prompting to download in Chrome.](https://trello.com/c/385ejwxr/8221-1-rise-player-downloads-for-linux-and-raspbian-open-in-new-tab-instead-of-prompting-to-download-in-chrome)

**Comment by btfrise** [comment]
Andre fixed this but requested I leave open.

**Comment by rudibravo** [comment]
@btfrise we fixed the issue with today's release. Can you please verify and close? Thanks
