### ISSUE TITLE
Remove EXIF Orientation Metadata to Images and Pre-process rotation right after download in Local Storage Module

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-launcher-electron#748]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: All Supported
- Player Version: 2018.07.05.13.06
- Viewer Version: 2-01-201806011112 / Latest

##### What is the expected behavior?

Images with EXIF Orientation Metadata are displayed in Image Widget according to whatever rotation value that metadata specifies.

##### What is the actual behavior?

The images are displayed as is, without considering any EXIF Orientation configuration. This does not match the rotation that could be seen in regular image viewer tools, or in thumbnails in our Storage Server that don't have any EXIF Orientation metadata, and are rotated when being generated.

This is a widget related issue, but the proposed solution is at Local Storage level as described in documents below.

##### What steps can be taken to replicate the problem? 

1. Download an image with EXIF metadata like: https://storage.googleapis.com/risemedialibrary-7fa5ee92-7deb-450b-a8d5-e5ed648c575f/landscape_3.jpg
1. Reference it from a simple HTML document as a CSS background image, or using a simple img tag.
1. To see the same effect in a presentation, upload the same image to Rise Storage, and create an image widget pointing to it in a presentation. The thumbnail will consider the EXIF rotation, but the displayed image won't.

More details on the original widget image issue 
https://github.com/Rise-Vision/widget-image/issues/154

and on the documents referenced by the content request card:
https://trello.com/c/IT3rU5DX/4486-5-content-request-local-storage-module-remove-exif-orientation-for-images

**Comment by santiagonoguez** [comment]
@sheadarlison Issue created. follow up on https://github.com/Rise-Vision/widget-image/issues/154

**Comment by sheadarlison** [comment]
Closing and moving to storage server

https://github.com/Rise-Vision/storage-server/issues/287
