### ISSUE TITLE
If a required site is not available when Player starts, it doesn't tell you what is not available, and just starts the Player.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#749]
- Operating System Version: All
- Player Version: RisePlayerElectron 2018.07.09.20.01 Free
- Viewer Version: 2-01-201806252012

##### What is the expected behavior?
The Player should indicate what cannot be accessed when any required sites are not available.

##### What is the actual behavior?
The Player will countdown and start, complete with any issues due to the site not being available. This means that part of the Presentation or Display will not run correctly, without a clear indication as to what the issue is.

##### What steps can be taken to replicate the problem? 
Install the Player with the network running, then disconnect the internet and restart the device. Notice the Player will not notify what it cannot reach, it will start the countdown, then the player, then show the offline message. This is a crude recreation of what the user was running into. For them, services.risevision.com was not available, but everything else was. Had we notified the user what was not available upon the Player starting (after that network requirement was not available) that would have been far easier for the user to correct without us.

Better to report the error to fix immediately, rather than part of the Presentation or Display not working correctly, and frustrating the user.

**Comment by tejohnso** [comment]
@robb-price @btfrise This is ready for confirm / close

**Comment by robb-price** [comment]
Verified and Closed.
