### ISSUE TITLE
Files With Multiple ' Not Playing

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-launcher-electron#752]
- Operating System Version: 64-bit Microsoft Windows 10 Pro
- Player Version: RisePlayerElectron 2018.07.26.19.26 Licensed

##### What is the expected behavior?
Files with multiple ' in the file-name play without issue.

##### What is the actual behavior?
Local-storage is not handling filename with more than one ' character in the name. A 403 Error is recorded in logs when attempting to download the file. Appears to be an issue on players using RLS and not Rise Cache players.

##### What steps can be taken to replicate the problem? 

1. Add a file to storage with more than one ' in the file-name.
2. Add the file to a presentation.
3. Play the presentation on a display.
4. Developer Console shows many ERR_CONNECT_REFUSED errors when attempting to download the file.
5. Local-storage logs show numerous 403 Forbidden errors.

**Comment by btfrise** [comment]
Confirmed fixed.
