### ISSUE TITLE
Users with folders of images or video in Presentations are sitting on "please wait while your image is downloading" message

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#754]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: 64-bit Microsoft Windows 10 Pro
- Player Version: RisePlayerElectron 2018.08.02.14.01 Licensed
- Viewer Version: 2-01-201807181450

##### What is the expected behavior?
Files from an image folder should download and play on a Display.

##### What is the actual behavior?
The Player is sitting on a "please wait while your image is downloading" message, while all content is downloading to the appropriate folder. Nothing ever happens, it just sits on that folder.

##### What steps can be taken to replicate the problem? 
1. Add some image files to a folder.
2. Add that folder to your Presentation using the Image Widget
3. Play the Presentation on a Display, notice it sits on the "please wait while your image is downloading" message and never plays the images.

The appropriate Display ID's and SC Sessions are available if needed.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) User Blocked: issue 754 - Users with folders of images in Presentations are sitting on "please wait while your image is downloading" message](https://trello.com/c/Tgelsxja/8432-1-user-blocked-issue-754-users-with-folders-of-images-in-presentations-are-sitting-on-please-wait-while-your-image-is-downloadin)

**Comment by PatrickA-RiseVision** [comment]
This also appears to be happening when playing folders of videos.  See https://risevision.zendesk.com/agent/tickets/26174

**Comment by robb-price** [comment]
@PatrickA-RiseVision This is occurring when one of the folders in the Presentation only has 1 item in it. A workaround is to remove that folder, and use the appropriate Widget to point to the single file.

This is still an issue, but at least we have a workaround for the time being.

**Comment by rudibravo** [comment]
This is being tracked now on https://github.com/Rise-Vision/widget-image/issues/167
