### ISSUE TITLE
Rise Player going to white screen after scheduled reboot

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#755]
- Operating System Version: 64-bit Microsoft Windows Embedded Standard
- Player Version: RisePlayerElectron 2018.08.02.14.01 Free
- Viewer Version: 2-01-201807181450

##### What is the expected behavior?

Rise Player should start up successfully every-time the media player is rebooted.

##### What is the actual behavior?

When the scheduled reboot occurs, Rise Player fails to start and will often lead to a white screen, but it doesn't always happen. It seems that viewer is crashing.

##### What steps can be taken to replicate the problem? 

NOTE: This only happens on a specific Display -- it may be related to the network environment.

1. Set a scheduled reboot for the Display.
2. Watch Rise Player after the reboot occurs and it will sometimes go to a white screen.

**Comment by kaden-rise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) User Blocked: Issue 755 - Rise Player going to white screen after scheduled reboot](https://trello.com/c/rRanAGiN/8433-1-user-blocked-issue-755-rise-player-going-to-white-screen-after-scheduled-reboot)

**Comment by btfrise** [comment]
This is included in issue #749 closing.
