### ISSUE TITLE
RLS won't play images in a folder if the same structure is in Trash

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#756]
- Operating System Version:  arm Raspbian GNU/Linux 9.4 (stretch) & 64-bit Microsoft Windows 10 Pro
- Player Version: RisePlayerElectron 2018.08.02.14.01 Licensed
- Viewer Version: 2-01-201807181450

##### What is the expected behavior?
Images in a folder in Rise Storage should play as a slideshow when the folder is selected in the Image Widget.  If the folder is modified, the Image Widget should play the updated contents of the folder.

##### What is the actual behavior?
When the same file and folder structure exists in Trash and the folder, "Files are Downloading" indefinitely on Rise Player, though it works as expected in preview in the app.

##### What steps can be taken to replicate the problem? 

1. Create a folder in Rise Storage, upload at least two images (otherwise you will encounter issue 167)
2. Delete the images from the folder.
3. Upload the same two images again.  Make sure the file names are the same as they were.
4. Create a presentation with an Image Widget that is set to play the folder you created in step 1.
5. Schedule the presentation to a display.  It will say, "Please wait while files are downloading"

Some additional notes for after you've replicated the problem:
- You should notice that Trash has the same folder structure as the files you've uploaded to storage.
- If you try deleting the files from storage, weird stuff seems to happen.  On my display, it was acting like no files were in the folder, even if I restarted Rise Player and deleted the local storage folder from %localappdata%/rvplayer/modules.
- You can work around it by renaming the original folder, then pointing the presentation to the new folder.  This is a good workaround if there's only 1 presentation pointing to the folder, but it doesn't scale well.

**Comment by tejohnso** [comment]
@PatrickA-RiseVision This should be corrected now, please verify and close.

**Comment by PatrickA-RiseVision** [comment]
This appears to be resolved.  Thanks!
