### ISSUE TITLE
Storage: if a file exists in trash, it will display instead of a file with the same path and filename in storage

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#757]
### What is the expected behavior?
Files uploaded to Storage should display correctly in Storage and in Presentations.

### What is the actual behavior?
If a file already exists in trash, and a file with the same name is uploaded to the same path in Storage, the file preview and the image in presentations are replaced with the file from Trash.

### What steps can be taken to replicate the problem?
1. Upload a file to storage.
2. Run that file on a presentation using the Image Widget (single image).
3. Move the file to trash.
4. Name a different file the same thing on your machine.
5. Upload the file you renamed in 4 to storage.

The preview in Storage should be of the file you trashed.  Your display should also not update.  Try downloading the file.  The correct file seems to get downloaded in spite of the preview.

Extra credit:
1. Rename the file in storage -- just add a 2 or something at the end of the file name.
2. Click on "Presentations" (or anywhere else in the app).
3. Click on "Storage" (Refreshing didn't seem to work here when I was playing with it).  -- The preview in Storage should now be correct for the renamed file.
4. Change the file's name back to what it was originally.
5. Click on "Presentations" (or anywhere else in the app).
6. Click on "Storage" (Refreshing didn't seem to work here when I was playing with it). -- The preview in Storage should be for the wrong file again.

Extra credit 2:
1. If you've manipulated the file name, change it back to the file name of the file in Trash.
2. Delete the file from Trash.
3. Check the file in Storage.  Repeat the steps above as needed.  For some reason, it's still broken, even after you take the file away in Trash.

**Comment by PatrickA-RiseVision** [comment]
this replaced https://github.com/Rise-Vision/rise-vision-apps/issues/720

**Comment by rudibravo** [comment]
@tejohnso @andrecardoso @ezequielc @PatrickA-RiseVision so what I found out investigating this issue is that the Rise Player is working correctly. Since the images are cached (both on client side and google image proxies) it might take up to 1 day for the thumbnail and apps related information to update, we could decrease it but it might increase costs, so I don't think it's worth for covering such small scenario. Thoughts?

**Comment by PatrickA-RiseVision** [comment]
@rudibravo I will try to replicate again on my display, but assuming it will work as it did when you tested most recently I agree.  I only had a single affected user on this, and we were able to work her around it by just naming the file differently.  

I will try to get this re-tested by tomorrow morning.

**Comment by PatrickA-RiseVision** [comment]
I can still replicate the problem.  http://www.youtube.com/watch?v=RBdJUSXOEuI

**Comment by rudibravo** [comment]
@PatrickA-RiseVision thanks, will take a look

**Comment by andrecardoso** [comment]
@PatrickA-RiseVision we deployed a change in messaging service to fix the problem of the files not updating on the display. Can you please validate and close this? Thanks.

**Comment by rudibravo** [comment]
@PatrickA-RiseVision @andrecardoso just to make sure, for now we are only fixing the Display part of the issue. We have a separate issue for the thumbnail not updating https://github.com/Rise-Vision/rise-vision-apps/issues/733

**Comment by tejohnso** [comment]
@PatrickA-RiseVision As @rudibravo mentioned, we have a separate issue for the thumbnail part of this issue. 

As for the display part, I do believe it has been corrected as far as the player loading the new image with the same name as the older image in trash. The only problem now is the message from the widget indicating that the file has been moved to trash isn't removed by the widget when the new image is uploaded. 
![moved-to-trash-overlay](https://user-images.githubusercontent.com/1511535/46027612-47747800-c0bc-11e8-8af7-36bfbebd7565.png)

I will open a separate issue for the widget. 

I think this issue can be closed. Please confirm

**Comment by PatrickA-RiseVision** [comment]
This can close.
