### ISSUE TITLE
Display Control Failing to Activate

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-launcher-electron#764]
- Operating System Version: 64-bit Microsoft Windows 10 Enterprise
- Player Version: RisePlayerElectron 2018.09.10.12.32 Licensed
- Viewer Version: 2-01-201808201721

##### What is the expected behavior?
The display should turn on and off with display control. Customer has verified the correct inputs are being sent to the display by manually performing them.

##### What is the actual behavior?
Display control generates an error in logging and does not work. 

##### What steps can be taken to replicate the problem? 
1. Setup display control according to display specifications and https://github.com/Rise-Vision/display-control-module.
3. Schedule a time for the display to go offline.
4. The presentation will switch to a black screen as expected, but the display will remain powered on.

**Comment by tejohnso** [comment]
@colby-maughan Can you confirm this is corrected on the latest player?

**Comment by tejohnso** [comment]
Closing - please re-open if necessary.
