### ISSUE TITLE
Storage: The Files could not be loaded. java.lang.IllegalArgumentException: Task size too large

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#766]
##### What is the expected behavior?
Files in storage are listed when accessing storage.

##### What is the actual behavior?
An error is returned and storage appears to be empty when accessing storage.  The error is not clear about what the problem is.

![image](https://user-images.githubusercontent.com/40774237/45965061-d79fb800-bffd-11e8-8d71-d3c38899d3ac.png)

##### What steps can be taken to replicate the problem? 

This only appears to be affecting one company.  I'm not sure at this time how to replicate in another company.

1.  access storage for an affected company.

**Comment by tejohnso** [comment]
@PatrickA-RiseVision please confirm and close

**Comment by PatrickA-RiseVision** [comment]
I haven't heard back from the customer, but I'm confident since I can no longer replicate the issue that it is resolved.
