### ISSUE TITLE
Player window is not set to *alwaysOnTop*

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher-electron#767]
- Operating System Version: windows
- Player Version: any
- Viewer Version: any

##### What is the expected behavior?
When starting a presentation with a custom resolution smaller than the screen size, the player window should not be obscured by other windows that are moved over it

##### What is the actual behavior?
The player window is obscured by other windows if they're dragged in front of it.

##### What steps can be taken to replicate the problem? 

1. Use a small custom resolution for a display
1. Drag a window in front of the player window

@alanclayton @justinsmith1 @robb-price fyi

**Comment by kaden-rise** [comment]
@tejohnso This looks to be fixed. I opened up Notepad, then started Rise Player. I pressed Alt+Tab to switch over to Notepad, but Rise Player remained on top. Is that the behavior we're looking for?

**Comment by tejohnso** [comment]
@kaden-rise Yes. Thanks.
