### ISSUE TITLE
Images deleted from a folder will continue to play in Image Widget

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#768]
- Operating System Version: 64-bit Ubuntu 14.04.4 LTS
- Player Version: RisePlayerElectron 2018.09.24.17.58 Licensed
- Viewer Version: 2-01-201808201721
--

##### What is the expected behavior?
When a folder running in an Image Widget is updated in Rise Storage, the same updates are reflected in the Image Widget on connected displays.

##### What is the actual behavior?
When a folder running in an Image Widget has files deleted from it in Rise Storage, those images continue to run on the display as though they were in Storage.

##### What steps can be taken to replicate the problem? 

1. Create a presentation with a placeholder containing an image widget pointing to a folder of images.
1. Schedule it to run on a display, let it download the files from the folder.
1. Delete an image from the folder in Rise Storage.
1. Delete the image from Trash.
1. The image will continue to run on the display as though it were part of the folder.

**Comment by tejohnso** [comment]
@PatrickA-RiseVision I think this should be closed as duplicate. See my comment on [the card](https://trello.com/c/aeoQKKlx/4743-3-defect-768-images-deleted-from-a-folder-will-continue-to-play-in-image-widget)

**Comment by PatrickA-RiseVision** [comment]
I agree, this seems like it may be a duplicate of https://trello.com/c/7YPNp9eE/4708-5-defect-765-rls-out-of-sync-after-offline-updates @tejohnso
