### ISSUE TITLE
Rise Player is behind the Dock, Launcher and TopBar in GNOME when there are multiple monitors

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#770]
- Operating System Version: Ubuntu 18.04 / GNOME
- Player Version: RisePlayerElectron 2018.10.09.20.34 Licensed
- Viewer Version: 2-01-201808201721

##### What is the expected behavior?
Rise Player should be full screen, and on top of all other applications.

##### What is the actual behavior?
Rise Player does not appear to be full screen.  It's possible to obscure Rise Player with other applications by hitting Alt + Tab.  GNOME's launcher, dock and topbar appear on top of Rise Player, even when they are set to hide automatically.  I can't seem to replicate this when there is only 1 display in use.

##### What steps can be taken to replicate the problem? 

1. Install the Rise player on Ubuntu 18.04
1. Connect 2 monitors to the media player
1. Set up the displays in a matrix
1. Make sure Dock is set to Auto-Hide (Settings -> Dock -> Auto-hide the Dock)
1. Follow this article to extend Rise Player to use multiple displays: https://help.risevision.com/hc/en-us/articles/115003613806-How-can-I-setup-Rise-Player-to-use-multiple-displays-
1. Reboot
1. Rise Player will be running, but Launcher, Dock and Topbar will all be on top of it as seen in the screenshot.

**Comment by rudibravo** [comment]
This is also reproducible on Ubuntu 16.04 that is using custom resolutions as described in [this help center article](https://help.risevision.com/hc/en-us/articles/115003613806-How-can-I-setup-Rise-Player-to-use-multiple-displays-).

**Comment by rudibravo** [comment]
Closing as we don't support this configuration on Linux.
