### ISSUE TITLE
Image Widget: Empty Folder set as PUD Placeholder shows "The selected folder doesn't contain any images"

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#773]
- Operating System Version: Windows 10 Pro
- Player Version: RisePlayerElectron 2018.11.02.11.22 Licensed
- Viewer Version: 	2-01-201810182053

##### What is the expected behavior?
When an Image Widget running a folder is the PUD placeholder for a presentation, the presentation should end and the next presentation should appear as soon as there are no remaining images to show in that folder.

##### What is the actual behavior?
When an Image Widget running a folder is the PUD placeholder for a presentation, and that image folder is empty, the error "The selected folder does not contain any images" appears for a few seconds before moving on to the next presentation.

##### What steps can be taken to replicate the problem? 

1. Create a presentation that contains a Placeholder with only a single Image Widget pointing to an image folder with any number of images.  Make that Placeholder the PUD Placeholder.
1. Create a schedule running 2 or more presentations.
1. Include the presentation created in Step 1 into the Schedule created in Step 2, and set it to PUD.
1. Run the schedule on a Display.
1. Delete all the images from the image folder.
1. An error message will appear for a few seconds in place of the PUD placeholder, before the next presentation is loaded.

**Comment by stulees** [comment]
@PatrickA-RiseVision Unless I'm misunderstanding, what you describe sounds like expected behaviour. When the widget is targeting a folder that has no files, it is built to display that message _"The selected folder does not contain any images"_ for 5 seconds before informing Viewer it is Done, in which case because it is the PUD placeholder for that presentation, Viewer will cycle to the next item in its schedule. 

Can you clarify what the issue is? Thanks

**Comment by PatrickA-RiseVision** [comment]
@stulees the issue is that if the schedule plays through the presentation on PUD, a white slide with the error text on it is displayed before moving onto the next slide if there are no images to show.

The workaround is to always show images, but the affected user doesn't want images in the presentation when they have none to show.

**Comment by stulees** [comment]
@PatrickA-RiseVision It sounds like the only option here then is to have the Widget forgo showing a message and delaying 5 seconds, instead inform Viewer immediately that the Widget is _Done_. This is not ideal in the scenario of the widget being the sole placeholder in a presentation and the presentation is the sole item in the schedule. It will create an intensive loop of Done <> Play between Widget and Viewer. @sheadarlison Thoughts here?

**Comment by sheadarlison** [comment]
@stulees If it was the sole placeholder/presentation in the schedule the alternative is that the display would sit on an error message the entire time, I think the loop is better than that. I also think the use case of sole placeholder/presentation with PUD set is unlikely. 

Thoughts?

**Comment by stulees** [comment]
@sheadarlison Currently with the sole placeholder/presentation in the schedule scenario, it sits on error message. So just to clarify, you would prefer the continuous loop of Done <> Play and show nothing on screen in that scenario, correct? This is what will occur if we implement no longer delaying _Done_ for 5 seconds with an error message, regardless of PUD selected or not.

**Comment by sheadarlison** [comment]
@stulees Yeah I think the continuous loop is better than showing an error message but lets get a second opinion. I'll talk to Alan when he's back from lunch and see if he agrees.

**Comment by sheadarlison** [comment]
@stulees Alan agrees, lets change the behaviour.

**Comment by stulees** [comment]
@sheadarlison Okay thanks
