### ISSUE TITLE
Rise Player doesn't receive Touch input intermittently

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#776]
- Operating System Version: 64-bit Microsoft Windows 10 Pro
- Player Version: RisePlayerElectron 2018.11.02.11.22 Licensed, RisePlayerElectron 2018.11.26.15.43 Licensed
- Viewer Version: 2-01-201811191457

##### What is the expected behavior?
Rise Player can receive touch input on Windows for interactive presentations.

##### What is the actual behavior?
Rise Player no longer receives touch input on Windows after some time.  We can still interact with the presentation content over a remote session.  Closing and reopening Rise Player seems to fix it.

##### What steps can be taken to replicate the problem? 

1.  Run the affected presentation on a touch device.
1.  After some time, try to interact with the Display.
1.  The Display does not receive touch input.

**Comment by PatrickA-RiseVision** [comment]
Closed pending further evidence that this is being caused by Player.

**Comment by PatrickA-RiseVision** [comment]
We have determined that the most likely cause is this electron defect: https://github.com/electron/electron/issues/8725

We were able to resolve it on a per-presentation basis by having Insteo implemented the solution recommended here: https://github.com/electron/electron/issues/8725#issuecomment-350786200

The permanent solution would be to fix this in Rise Player.

**Comment by tejohnso** [comment]
Closing this as interactivity is not priority as per @alanclayton

**Comment by carlokid** [comment]
@PatrickA-RiseVision what happen on this

> We have determined that the most likely cause is this electron defect: [electron/electron#8725](https://github.com/electron/electron/issues/8725)
> 
> We were able to resolve it on a per-presentation basis by having Insteo implemented the solution recommended here: [electron/electron#8725 (comment)](https://github.com/electron/electron/issues/8725#issuecomment-350786200)
> 
> The permanent solution would be to fix this in Rise Player.

Were you able to resolve it? Would like to ask what version of electron you are using. Currently my version is 2.0.6 and issue is still there. Someone says, upgrading to 3.x might resolve the issue. I haven't tried yet though as I don't have the kiosk machine right now, maybe sometime soon.

**Comment by PatrickA-RiseVision** [comment]
@carlokid applying the fix in the comment to each presentation appeared to resolve the issue at first, but it still happens specifically when the machine is rebooted by the app at 2:00am.  It doesn't happen if we reboot it ourselves, nor does it seem to happen if we let the app reboot the machine at an arbitrary time in the day.

Something I've noticed while working with this on the weekend is that touching the screen seems to control the mouse instead of acting like a click when it's happening.  It's as though Windows thinks the touch screen is a track pad or something, but that can't be the case because it works as expected everywhere else -- even if I just open the Chrome console from within the app.
