### ISSUE TITLE
Schedule URL's load slower on Display than they used to prior to the latest Player upgrade

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#781]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

- Operating System Version: 64-bit Ubuntu 14.04.5 LTS
- Player Version: RisePlayerElectron 2019.01.07.21.55 Licensed
- Viewer Version: Shows N/A: https://goo.gl/sHzjVq

##### What is the expected behavior?
The URL's should load the same way that they load in preview. 

##### What is the actual behavior?
Now, as of a recent update it seems that these are being treated as separate browser instances, or webpages, and each slide transition will completely reload the webpage, causing a 2-3 second page-load between slides, even as the schedule repeats.

##### What steps can be taken to replicate the problem? 
Use this Schedule to test: https://apps.risevision.com/schedules/details/95b8c6be-8ea5-4e20-95e0-f3d85cbe5260?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by tejohnso** [comment]
https://trello.com/c/Z4Yxj6Fo/4944-3-defect-781-schedule-urls-load-slower-on-display-than-they-used-to-prior-to-the-latest-player-upgrade
