### ISSUE TITLE
Untangle firewall is flagging our Windows installer on download

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-launcher-electron#783]
**Describe the bug**
Untangle firewall sees both of our windows installers as a virus.

Details about the Untangle firewall can be found at their website: 
https://www.untangle.com/

**Reach**
This is affecting any user using Untangle firewall in their environment

**Impact**
Product is not usable

**To Reproduce**
attempt to download our installer with Untangled in the evn. Here is the error output:

Virus Blocker found virus [Gen:Heur.BZC.ONG.Boxter.222.21754894] http://install-versions.risevision.com/installer-win-64.exe

Causal Event: VirusHttpEvent 
{ 
"timeStamp": "2019-02-01 15:17:13.49", 
"virusName": "Gen:Heur.BZC.ONG.Boxter.222.21754894", 
"appName": "virus_blocker", 
"requestLine": "GET http://install-versions.risevision.com/installer-win-64.exe",

**Expected behavior**
installer is not flagged

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by tejohnso** [comment]
False positive report submitted.

**Comment by tejohnso** [comment]
Fixed by removing javascript usage (mshta) in initial run script.
