### ISSUE TITLE
Rise Storage: Presentation Backgrounds and Placeholder Backgrounds don't update when the file is updated in storage.

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#784]
**Describe the bug**
Images in Rise Storage used as Background Images for Presentations or Placeholders do not update if the file in Storage is replaced with a new file with the same name.

**Reach**
This seems to be affecting anyone who is using Background Images in this way, but we only have 1 user reporting it.

**Impact**
The workaround would be to use an Image Widget instead, and set a low Z-order if it must be behind another item.

**To Reproduce**
1. Upload an image to Rise Storage, name it something unique like "Test1.jpg".
2. In a new presentation, create a placholder.
3. In the presentation properties for the placeholder created in 2, set the background image to Test1.jpg.
4. Save and publish the image to a Display.
5. In Rise Storage, replace Test1.jpg with a different image named the same thing.

**Expected behavior**
The image should have updated to reflect what is in Rise Storage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04, Windows 10

**Additional context**
This is similar to the issue we have seen with files not updating in Editor and their thumbnails.  With the Image Widget, I don't seem to have this issue, but I can replicate it in Preview and on my Display by using a Background Image.

**Comment by tejohnso** [comment]
@alanclayton I think this is exactly as you mentioned in SoS and @PatrickA-RiseVision has suggested that:

>The workaround would be to use an Image Widget instead, and set a low Z-order if it must be behind another item.

I think this is known behaviour that we're not going to address given we're moving to templates and there's a reasonable work around, so I'm going to close this unless either of you have strong objections. Feel free to re-open.

**Comment by alanclayton** [comment]
@tejohnso Agreed.
