### ISSUE TITLE
Older Players that have the Core and Viewer URL in the INI file, are showing a loading spinner when you update the Presentation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#785]
**Describe the bug**
We have older units with viewerurl=http://rvashow.appspot.com/Viewer.html in the ini file. That's going to break widgets because we expect viewer to be at viewer.risevision.com.

When the Presentation or Schedule is updated, it goes to a loading spinner, and will not change until you reboot the device.

**Reach**
This has the potential to affect all users who have this in the RiseDisplayNetworkII.ini file from a previous install.

**Impact**
The only correction is to remove those lines from the INI, or reinstall completely.

**Desktop (please complete the following information):**
 - OS: Linux and Windows, all versions.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Issue 785: Older Players that have the Core and Viewer URL in the INI file, are showing a loading spinner when you update the Presentation](https://trello.com/c/ca7NKlRt/9430-3-issue-785-older-players-that-have-the-core-and-viewer-url-in-the-ini-file-are-showing-a-loading-spinner-when-you-update-the-pr)

**Comment by tejohnso** [comment]
This was corrected in February.
