### ISSUE TITLE
Rise Player loads indefinitely / "schedule not set, cannot calculate uptime."

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#789]
**Describe the bug**
A growing number of Displays are reporting the error " schedule not set, cannot calculate uptime." and showing the loading screen/wheel indefinitely.  Users are reporting they can work around it by restarting repeatedly but it's inconsistent.

**Reach**
I currently have a list of 16 affected Displays.  We have been receiving more reports throughout the day.

**Impact**
This is preventing Rise Player from showing content unless they happen to work around it temporarily with a restart.  The workaround is inconsistent, so it's not reliable.

**To Reproduce**
I haven't been able to replicate this on my Display.  I will update with steps to reproduce if I identify them.

**Expected behavior**
Content would play on Rise Player.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I will be linking a list of affected Displays and available SC sessions in the card.

**Comment by tejohnso** [comment]
https://trello.com/c/5LoBRUrD/5073-2-defect-789-rise-player-loads-indefinitely-schedule-not-set-cannot-calculate-uptime
