### ISSUE TITLE
Search Functionality is very slow when running in Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#790]
**Describe the bug**
When using the Google Sheets search functionality via a webpage in this Presentation, it searches very slow. In Preview, this does not occur.

**Reach**
So far only one user has reported this issue.

**Impact**
It works, but it is very slow.

**To Reproduce**
1. Open the affected Presentation (which is included in the Trello Card), and notice that in Preview, the search functionality is quick and responsive.
2. Connect to the SC session of a Display running this Presentation (which is included in the Trello Card) and notice the search functionality is very slow.

**Expected behavior**
The search should not be slow when running on the Display.

**Desktop (please complete the following information):**
32-bit Microsoft Windows 7 Professional, Windows 10 32 Bit

**Comment by tejohnso** [comment]
@robb-price Findings for this issue are on [this card](https://trello.com/c/52nMka1w/5079-3-defect-790-search-functionality-is-very-slow-when-running-in-player). To summarize, this is happening outside of player / viewer with chrome 32 (up to version 64 or so). 

The recommendation to correct is to use a 64bit version of player, or ask Insteo to investigate with a 32-bit, older version of chrome where they can reproduce the issue and perhaps find a fix with their javascript implementation.

Here's some log data in case Insteo wants to take a look:

```
insteo.js:336 Instructions: 
GetAppDesignInstructionList.txt
insteo.js:140 Data: 
https://spreadsheets.google.com/feeds/list/1PCWUTGGEugI2O3UqbRWNCfL81Pp5R2cLvokL-Ei4FBY/1/public/values
jquery.js:3761 [Violation] Handler took 2320ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 1752ms
[Violation] Long running JavaScript task took 2323ms
[Violation] Forced reflow while executing JavaScript took 36ms
[Violation] Long running JavaScript task took 1623ms
jquery.js:3761 [Violation] Handler took 54ms of runtime (50ms allowed)
index.html:38 [Violation] Handler took 235ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 160ms
[Violation] Long running JavaScript task took 237ms
jquery.js:3761 [Violation] Handler took 2236ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 1747ms
[Violation] Long running JavaScript task took 2237ms
jquery.js:3761 [Violation] Handler took 2286ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 1792ms
[Violation] Long running JavaScript task took 2295ms
jquery.js:3761 [Violation] Handler took 2291ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 1815ms
[Violation] Long running JavaScript task took 2316ms
jquery.js:3761 [Violation] Handler took 2275ms of runtime (150ms allowed)
[Violation] Forced reflow while executing JavaScript took 1762ms
[Violation] Long running JavaScript task took 2280ms
[Violation] Long running JavaScript task took 378ms
[Violation] Long running JavaScript task took 301ms
[Violation] Long running JavaScript task took 310ms
```

@alexey-rise fyi
