### ISSUE TITLE
Rise Player checking for the wrong AWS domain

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#792]
**Describe the bug**
Rise Player is configured to connect to s3.amazonaws.com however, the URL it should be connecting to is aws.amazon.com/s3/

**Reach**
Any users with a firewall

**Impact**
Severe.

**To Reproduce**
N/A

**Expected behavior**
Rise Player should try to connect to aws.amazon.com/s3/

**Screenshots**
![image](https://user-images.githubusercontent.com/33877348/54547735-f444f900-496b-11e9-923e-de5ffdd37cca.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by tejohnso** [comment]
@kaden-rise can you attach the ticket or a screenshot to this?

**Comment by kaden-rise** [comment]
> @kaden-rise can you attach a screenshot to this?

Done!
