### ISSUE TITLE
HTML Template fails to load on Windows

### ISSUE THREAD

**Issue by andrecardoso** [Rise-Vision/rise-launcher-electron#795]
**Describe the bug**
Player shows an error when loading a HTML Template presentation from a schedule with multiple items including non HTML template content.

**Reach**
How many users is this affecting, or might it affect?
Not many, as it only affects Windows displays that have schedules with both HTML templates and other content items.

**Impact**
How severe is it for any affected user; is there a known workaround?
The workaround is to change the schedule to contain only HTML Templates so that player loads it outside of viewer.

**To Reproduce**
1. Configure a schedule containing a HTML Template and a URL Item
2. Start the player

**Expected behavior**
HTML template loads correctly

**Screenshots**
The error message indicates that player is using a wrong URL to load the template:

![windows-error](https://user-images.githubusercontent.com/161674/57888132-a16ead00-7807-11e9-9139-9bfb2900d4b9.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
It works on Linux

**Comment by tejohnso** [comment]
@andrecardoso Please confirm and close.

**Comment by andrecardoso** [comment]
@tejohnso looks good. Thanks!
