### ISSUE TITLE
Raspbian Jesse is no longer supported as Debian Stable.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#798]
**Describe the bug**
Our advertised supported version of Raspbian (Jessie) is no longer supported by Debian.

**Reach**
All Raspberry Pi users Displays.

**Impact**
Medium / High. 2 IT Taylor's have reported to us that they would like us to support a more current (and supported) version of Debian, like Stretch or Buster.

**To Reproduce**
N/A

**Expected behavior**
We always advertise that we support a current version of Raspbian OS.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian / Pi

**Additional context**
N/A
-----

NOTE: do not add Display ID, Company ID or ScreenConnect links to this issue. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue.

**Comment by alanclayton** [comment]
@btfrise I do not consider this a defect. It is a feature request that will be addressed this quarter. Can you please close.

@andrecardoso FYI.
