### ISSUE TITLE
Some Displays are Showing "Missing License" regardless of license status.

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-launcher-electron#799]
**Describe the bug**
Displays are showing "Missing License" despite having a license activated. 

**Reach**
Unsure on current reach, but this has potential to affect a lot of users.

**Impact**
Have tried various things to try and negate the issue, as far as I can tell there is not a workaround. Relicensing, restarting, rebooting, etc. 

**To Reproduce**
Add a display to the same schedule as the other display with the issue - it will immediately have the error.

**Expected behavior**
When a display is licensed, it should not receive this error.

**Screenshots**
https://drive.google.com/file/d/1Vl2PWoS_Q0WXE45Nfjayu6rPfnXETp9v/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Potential impact to all operating systems, confirmed impact on Linux and ChromeOS

**Additional context**

-----

NOTE: do not add Display ID, Company ID or ScreenConnect links to this issue. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue.

**Comment by sheadarlison** [comment]
This was fixed.

**Comment by tejohnso** [comment]
Reopening this to track account suspension fix as a defect.

**Comment by tejohnso** [comment]
Fixed with https://github.com/Rise-Vision/core/issues/511
