### ISSUE TITLE
Installer cannot complete

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher-electron#801]
**Describe the bug**
When running the installer on the Player, the installation process does not complete. Instead it shows this error at the end.

*Affects all installers.

**Reach**
All users installing or upgrading the latest version of the installer.

**Impact**
No work around.

**To Reproduce**
1. Download the latest version of the Installer, and follow the steps to install. 
2. Once installation is completed, you get this error, instead of the Player completing:
![Screenshot (3)](https://user-images.githubusercontent.com/6862256/61212618-cfba1d00-a6d0-11e9-950b-51a3a8b035c7.png)

**Expected behavior**
Player should successfully complete and start.

**Desktop (please complete the following information):**
 - OS: Windows, Linux, Pi, Chrome

**Comment by alanclayton** [comment]
@robb-price @andrecardoso should this be closed?

**Comment by andrecardoso** [comment]
@alanclayton yes
