### ISSUE TITLE
Player does not disable screen blanking on Debian Buster

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-launcher-electron#803]
**Describe the bug**
Installing Rise Player on a newly formatted SD card running Buster results in the screen blanking after several minutes of running content. 

**Impact**
User has to manually disable screen blanking. I was able to do this with the following steps:

1. sudo nano /etc/xdg/lxsession/LXDE-pi/autostart
2. comment out @xscreensaver -no-splash
3. add the following lines:
 - @xset s noblank 
 - @xset s off 
 - @xset -dpms

**Comment by tejohnso** [comment]
Closed with https://github.com/Rise-Vision/rise-launcher-electron/pull/822
Thanks
