### ISSUE TITLE
Requests timing out during startup.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-launcher-electron#813]
**Describe the bug**
Display with Rise Player installed times out checking status of required URLs during every startup. The URLs are available on the Media Player and responding to ping at time of startup.

**Reach**
1 user has reported this issue.

**Impact**
There is a workaround. This is a nuisance to IT Taylor but we can manually intervene to get them running.

**To Reproduce**
1. Go to their Screenconnect session (see card)
2. Close Rise Player
3. Open Rise Player

**Expected behavior**
Rise Player should start without any timeout errors.

**Screenshots**
[Image 1](https://www.screencast.com/t/sP3CoJUd2E)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS

**Additional context**
I have checked all URLs through browser and they have access to all. I've also pinged services.risevision.com while running installer. No pings were lost, yet Rise Player was still timing out.

-----

NOTE: do not add Display ID, Company ID or ScreenConnect links to this issue. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue.

**Comment by btfrise** [comment]
[Screenconnect Link](https://connect.risevision.com/Host#Access/Santa%20Rosa%20Academy//145d7f96-6468-3fc5-9bac-fba70feef3fb)

**Comment by robb-price** [comment]
@tejohnso I have reached out to the user to see if we can get a machine outside of their firewall / network restrictions to test on, but should we close this issue and follow Issue #819 for this user block instead?

**Comment by tejohnso** [comment]
@robb-price I think we can leave this issue open until that PR is merged.

**Comment by tejohnso** [comment]
@robb-price closing as discussed, fixed with https://github.com/Rise-Vision/rise-launcher-electron/pull/820
