### ISSUE TITLE
Player is constantly logging LMS Disconnection errors on a small number of machines

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#815]
**Describe the bug**
Development has identified a handful of machines logging LMS Disconnection errors every few minutes.  On the players, it looks like content isn't updating until the player is rebooted.

**Reach**
Currently this is only affecting a handful of Displays we have identified.

**Impact**
Displays are showing content, but the media player must be rebooted to receive content updates.

**To Reproduce**
We have not reproduced this successfully.  We have a handful of existing cases where they are logging errors which I will share separately.  

**Expected behavior**
Player remains connected to LMS, and if there's a failure, it reconnects.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows Server 2016

**Additional context**
These Displays were identified by Development.  You can see the logs with the following query:

SELECT ts, event, event_details, installer_version 
FROM [client-side-events:Installer_Events.events20190905]
WHERE display_id  = 'DISPLAY_ID'
ORDER BY ts DESC

Details will be added to the card.

**Comment by santiagonoguez** [comment]
Not a bug. These displays were all running using different users on a single machine, which is not supported on Rise Player, and it seems they are competing for resources ( socket file, socket ports ).
