### ISSUE TITLE
Folder of Videos won't update after folder empties

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-launcher-electron#817]
**Describe the bug**
When using a video widget in 'folder of videos' mode, most changes to the folder in storage will update. But if you fully remove ALL videos from the folder, the widget will quit displaying, but adding videos to the folder

**Reach**
How many users is this affecting, or might it affect?
Only 1 we know of.

**Impact**
How severe is it for any affected user; is there a known workaround?

minimal impact, client has a work around for all use cases but 1

**To Reproduce**
1. Create a presentation that uses folder of videos
2. Add 2+ videos to the folder and run the presentation
3. add or remove 1 video 
4. The error will not show up
5. remove ALL videos 
6. No content will show
7. Add videos to the folder and the widget will not update

**Expected behavior**
When using the folder of videos mode of the video widget, removing all videos will quit playing content, but adding more videos to the storage folder after this will start playing those videos

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by santiagonoguez** [comment]
@tylermwight this has been fixed
