### ISSUE TITLE
Too many displays log "watchdog-restart" event

### ISSUE THREAD

**Issue by olegrise** [Rise-Vision/rise-launcher-electron#818]
**Describe the bug**
The number of displays reporting "watchdog-restart" event rapidly increased on 25-Aug-2019 when Player version 2019.08.26.16.13 rollout started. It's normal for this number to spike during rollout, but then it should go back to the level it was before. Before 25-Aug-2019 we had 3 displays reporting "watchdog-restart" event. After 2019.08.26.16.13 release was rolled out, we have ~1000 displays logging this even every day. Many of the displays log this even multiple times a day. The problem occurs on all types of OS.

**Reach**
Approximately 1000 displays.

**Impact**
Not sure.

**To Reproduce**
You can use the following query to get the number of displays affected on a selected date
```
#standardSQL

SELECT count(distinct display_id ), event_details FROM `client-side-events.Installer_Events.events*`
WHERE _table_suffix = FORMAT_DATE('%E4Y%m%d', "2019-09-02") 
and event = 'watchdog-restart'
AND installer_version IN ( SELECT MAX(m.version) FROM `client-side-events.Module_Events.modules_manifest`, unnest(modules) m where m.name = 'launcher' )
GROUP BY event_details

```
Or use this query to get the list of displays
```
SELECT display_id, ANY_VALUE(os) as os, count(display_id) as count, event_details FROM `client-side-events.Installer_Events.events*`
WHERE _table_suffix = FORMAT_DATE('%E4Y%m%d', "2019-09-02") 
and event = 'watchdog-restart'
AND installer_version IN ( SELECT MAX(m.version) FROM `client-side-events.Module_Events.modules_manifest`, unnest(modules) m where m.name = 'launcher' )
GROUP BY display_id, event_details
```

**Expected behavior**
A number of display logging "watchdog-restart" event should be close to 0 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
This issue might be related to #815.

-----

NOTE: do not add Display ID, Company ID or ScreenConnect links to this issue. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue.

**Comment by santiagonoguez** [comment]
@olegrise are you getting viewer disconnections on those displays ? or why are you relating this to 815 ?

**Comment by olegrise** [comment]
@santiagonoguez just guessing that there might be a correlation because both numbers are higher than usual.

**Comment by santiagonoguez** [comment]
@olegrise and those ~1000 displays where this problem is happening were updated to latest player ? so we can be sure this is really related to the upgrade. If that's the case maybe we should consider roll back, again :'(

**Comment by olegrise** [comment]
@santiagonoguez not all of those displays are updated to the latest player. In fact it doesn't look like the issue is related to the current rollout. Most likely the issue is in the Player and it was introduced some time ago in version 2019.08.26.16.13, not in this release. If we have something important in the current rollout, I'd say it's a low risk to finish the current rollout and then work on this issue.

**Comment by olegrise** [comment]
@santiagonoguez I checked just a few displays and there seems to be a correlation between LMS and Player reporting "watchdog-restart". See [here](https://docs.google.com/document/d/13xwWh1FJABcPeHWX4QWrrLifg14eke2lc0Hp0_inLAA/edit#bookmark=id.fg9njxkgz3a1).

**Comment by tejohnso** [comment]
Not a defect - see [entry](https://docs.google.com/spreadsheets/d/1TwQAoP525vijFFbrSUwK_lfI-aDnW0O1y11Y2O5-emA/edit#gid=1076349944&range=A77) in defect spreadsheet.
