### ISSUE TITLE
Certain Displays not receiving updates from the Messaging Service

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#829]
**Describe the bug**
Certain Displays playing templates do not update when changes are made to the template and published.

**Reach**
So far only 1 that I'm aware of.

**Impact**
Fairly severe, in this case the user cannot get their Weekly Lunch template to update on their Display so the students wouldn't be able to see the correct lunch items for the week.

**To Reproduce**
I cannot reproduce this behavior.

**Expected behavior**
Templates should always update on the Displays after changes are made and the Template is published.

**Desktop (please complete the following information):**
 - OS: Chrome OS 12499.51.0

**Comment by andrecardoso** [comment]
We manually restored the state of the affected displays and improved logs on messaging service to help investigating it in case it happens again in the future.

**Comment by colby-maughan** [comment]
@andrecardoso We're still running into instances of displays not updating presentation changes - I am continuing to add them to the LMS Disconection sheet. Blake asked me to re-open this one.
