### ISSUE TITLE
Certain displays are not receiving content updates

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-launcher-electron#832]
**Describe the bug**
Certain displays are not receiving updated content - only new content.

**Reach**
Currently looks to be 12 different users submitting tickets about this, potential for more.

**Impact**
Creating new presentations, folders in storage, or schedules tends to resolve the issue, but this is not an acceptable workaround for the majority of cases.

**To Reproduce**
I have been unable to reproduce the behavior on any displays that weren't already affected with the issue. I have tried to preserve storage folders and presentations that do experience the issue, though they only seem to cause problems on specific displays. 

**Expected behavior**
When a change is made to anything affecting a display, it should update on the display.

**Desktop (please complete the following information):**
 - This does not seem to be OS dependent so far - several different operating systems are experiencing the issue.

**Additional context**
A doc is currently being used to keep track of displays suffering from this issue - will attach to card.

**Comment by alanclayton** [comment]
Same behavior as described on recent defect #829
