### ISSUE TITLE
Rise Player on Raspbian does not control the TV using CEC as expected

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#834]
**Describe the bug**
Rise Player on Raspbian does not seem to control the TV with CEC correctly.
If Player has no content to play when it starts up, the TV remains off regardless what should be running on the schedule.
If Player has content to play when it starts up, the TV remains on regardless what should be running on the schedule.

**Reach**
We have had 1 report for 11 Displays from a user.
We were able to replicate this in the Rise Vision office at Plexpod.

**Impact**
Not severe; the workaround is to disable CEC on the TVs and manually control the TVs.

**To Reproduce**
1. Set up CEC on a Raspberry Pi Display.
2. Set up a schedule to play content on your Display.
3. Change the timeline of your schedule so that player does not have content to run.  CEC should shut the TV off, but doesn't.

**Expected behavior**
When your Schedule does not have any content to run because we are outside the timeline of the schedule, or outside the timeline of all playlist items, the TV is shut off.  When we are within the timeline of either the schedule or the playlist items, the TV should turn back on.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: arm Raspbian GNU/Linux 8.0 (jessie)
arm Raspbian GNU/Linux 9.4 (stretch)

**Additional context**
- In the office, we can verify that CEC is working by running the following commands:
`echo "on 0" | cec-client -s`
`echo "standby 0" | cec-client -s`
- In the office, we can't get CEC to work on the Display at all.  Player doesn't seem to control the state of the TV.
- At the customer site, it's more like CEC is "stuck" in whatever position it was last in when Player started.  This is different from what we observed in the KC office.

I'll share SC links privately.  CEC is currently off on the customer Display.  CEC is currently on in the KC office.

**Comment by andrecardoso** [comment]
Fixed in Player Release 2020.01.21.18.21

**Comment by PatrickA-RiseVision** [comment]
@andrecardoso we were finally able to test.  The Display shuts off as expected when the schedule cuts over, but we can't get it to turn back on when content is playing.  Can we reopen this?

**Comment by olegrise** [comment]
@PatrickA-RiseVision sure. Lets reopen. Thanks.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) [Issue #834] Rise Player on Raspbian does not control the TV using CEC as expected](https://trello.com/c/Srx6xK5G/408-1-issue-834-rise-player-on-raspbian-does-not-control-the-tv-using-cec-as-expected)
