### ISSUE TITLE
Scroll bars are incorrectly displayed on some templates

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-launcher-electron#836]
**Describe the bug**
Scroll bars show up on certain templates on player. Issue seems to be inconsistent between players though according to Creative testing. Only occurs when there is a single template scheduled, and only on some templates, such as the Scrolling Ticker or 5 Day Weather Forecast. On scrolling ticker, scrollbar size appears related to the message, as it constantly changes. Screenshots show some affected templates.

**Reach**
Currently one user has reached out about this.

**Impact**
The workaround is to schedule more than one template. The scroll bars should then disappear. 

**To Reproduce**
1. Add Scrolling Ticker as the only template in your schedule.
2. Observe the player.

**Expected behavior**
There should be no scroll bar.

**Screenshots**
Folder with a couple screenshots available below.

https://drive.google.com/open?id=1PmegRTz5SKJx-Z87epLtq-Xztp7AKejj

**Desktop (please complete the following information):**
 - OS: Linux, Windows, was not able to replicate on Chrome.

**Additional context**
SC Session to affected machine will be available on Trello card.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [Issue 836] Scroll bars are incorrectly displayed on some templates](https://trello.com/c/kF0DtzqP/401-2-issue-836-scroll-bars-are-incorrectly-displayed-on-some-templates)

**Comment by andrecardoso** [comment]
Fixed in version 2020.02.05.14.43 by disabling no-viewer mode

**Comment by mmeiers** [comment]
Opened Again
I'm seeing it on this display. https://apps-stage-0.risevision.com/displays/details/PT7VJ8T3D8HT?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

With this presentation when its the only template in the schedule. 
https://apps-stage-0.risevision.com/templates/edit/8d5052d8-aeb2-4193-92a6-a1798e87a33b/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

I don't have screen connect yet as I am having difficulties logging in with 2 step.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #836 - Scrollbars](https://trello.com/c/BC8U1c97/419-issue-836-scrollbars)

**Comment by olegrise** [comment]
**Update**:  I was only able to reproduce the issue on Pi running older version of Player 2019.11.13.22.21. As soon as I reinstalled Player, the scrollbars disappeared. I also tested on latest versions of Chrome OS and Electron Player and didn't see the issue.

@mmeiers looking at your [display](https://apps-stage-0.risevision.com/displays/details/PT7VJ8T3D8HT?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443) settings, it seems that you are using Pi with the latests version of Player, however, I wonder if you can do a clean reinstall and see if issue is still there. If it is, I might need access to your display to see what's going on there.

**Comment by mmeiers** [comment]
@olegrise Oddly enough I just checked and I don't see the scroll bards anymore without reinstall. Perhaps it needed to be rebooted. I think we can call this one closed. Thanks!

**Comment by olegrise** [comment]
Thanks @mmeiers
