### ISSUE TITLE
When a duration is set in the schedule, templates loop for that exact duration even if they are alone in the playlist

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#837]
**Describe the bug**
If a single template is in a schedule's playlist with an arbitrary duration, it will play for that exact duration and start over, as though the schedule is starting over.
This is different from the behavior schedules had previously, where a lone item in the schedule would just play forever.
It's causing situations wherein I create my first Image Slideshow template during onboarding, and only the first image is played because the default duration of each slide is 10 seconds and the default duration of the playlist item is also 10 seconds.

**Reach**
Any users who are setting durations manually, but notably this is affecting everyone who goes through the onboarding process right now due to a bug in onboarding that causes the default behavior to be 10s rather than PUD.

**Impact**
PUD can be enabled, or the duration can be set correctly, but since this is affecting new users they will need to know how to do that or reach out to support.

**To Reproduce**
1. Create a presentation from the Image Full Screen template.
2. Set multiple images in the template.
3. Create a schedule and add the Image Full Screen template you just built as a lone item, set its duration to 10s.
4. Assign the schedule to your test Display.

You should see only the first image play.  There is sometimes a brief flash as though the content is reloading.

**Expected behavior**
If only 1 item exists in the playlist, it should play indefinitely regardless of duration.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Confirmed on Windows 10 and Linux player.

**Additional context**
Apps defect 1494 is causing every new signup to encounter this if they pick the image slideshow.

**Comment by andrecardoso** [comment]
Fixed in Player Release 2020.02.05.14.43 and Chrome OS Player Release 2020.02.05.8680
