### ISSUE TITLE
Killing Rise Player with Ctrl + Shift + Q key combo causing file explorer windows to open

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#840]
**Describe the bug**
While Rise Player is running on a Windows machine, if you either press and hold CTRL + Shift + Q or spam Ctrl + Shift + Q to kill Rise Player, multiple file explorer windows will open as Rise Player is closing.

**Reach**
So far 1 user, but could be affecting anyone with a Windows Media Player.

**Impact**
It happens every time for the user in question. For them, even just tapping the Ctrl + Shift + Q combo once really quick causes file explorer windows to open as Rise Player is closing. When I'm remoted into their device, the issue only happens if I hold down the key combo or spam it multiple times.

**To Reproduce**
1. Start Rise Player on a test Windows 10 Media Player
2. Press and hold Ctrl + Shift + Q or spam Ctrl + Shift + Q
3. As Rise Player is closing you should see multiple file explorer windows popping up

**Expected behavior**
Closing Rise Player with the Ctrl + Shift + Q key combo should not result in file explorer windows opening regardless of how long or how many times the key combo is pressed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Operating System | 64-bit Microsoft Windows 10 Pro
Player Version | RisePlayerElectron 2019.11.22.22.36 Licensed
Viewer Version | 2-01-202002171445
Browser Version | Chromium 69.0.3497.128

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #840 -](https://trello.com/c/kNlK29oc/420-issue-840)

**Comment by andrecardoso** [comment]
We implemented a fix for this in version 2020.03.05.21.02 it is now on stable, new installs or player started with `--rollout-pct=100` will get it.
