### ISSUE TITLE
"Starting Rise Vision Player" notification banner showing over top of Rise Player after upgrade to 18.04

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-launcher-electron#843]
**Describe the bug**
After upgrading from Ubuntu 16.04 to 18.04 using the steps in [this guide](https://docs.google.com/document/d/129GfFLWbPxeEqRD2zdV3pHtYxeXn2hof6BwHiNyFnbA/edit#), the "Starting Rise Vision Player" notification banner shows over the top of Rise Player. It requires manual intervention to close the notification banner.

**Reach**
No users that I'm aware of, but happens on multiple test devices.

**Impact**
N/A

**To Reproduce**
1. Assign a Schedule containing a test Presentation to a Celeron/Pentium Media Player running our current 16.04 image
2. Upgrade the Media Player to 18.04 using the steps in [this guide](https://docs.google.com/document/d/129GfFLWbPxeEqRD2zdV3pHtYxeXn2hof6BwHiNyFnbA/edit#)
2. Reboot the Media Player
3. When Rise Player starts automatically the "Starting Rise Vision Player" notification banner appears and does not close without manual intervention.

**Expected behavior**
The "Starting Rise Vision Player" notification banner should close on its own and not appear on top of Rise Player.

**Screenshots**
![image](https://user-images.githubusercontent.com/33877348/76130357-c36c3280-5fc7-11ea-85ba-54255aaf2001.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04 64-bit

**Comment by tejohnso** [comment]
It appears that behaviour has changed from 16 to 18. While it used to go away automatically, it now seems to require some kind of user action. Even pressing the shift key will cause it to disappear after a couple of seconds. Since this pop up is not a crucial part of the process, I'm wondering if we should just remove it altogether. @olegrise @kaden-rise what do you think?

**Comment by PatrickA-RiseVision** [comment]
@tejohnso I agree, if it isn't too much effort just cut it completely.

**Comment by olegrise** [comment]
Agreed
